export const exampleCopy = {
  ru: {
    label: 'Учебный пример · вымышленные данные',
    title: 'Кому нужно дообучение?',
    intro: 'Посмотрите фрагмент урока, ответьте на вопрос и разберите результаты сотрудников. Документы и регистрация не нужны.',
    lesson: '1. Фрагмент урока', course: 'Информационная безопасность',
    lessonTitle: 'Неожиданное письмо с просьбой войти в аккаунт',
    paragraphs: ['В письме просят срочно подтвердить пароль по ссылке. Даже знакомое имя отправителя не доказывает, что письмо безопасно.', 'Не открывайте ссылку и не отвечайте на письмо. Откройте рабочий сервис привычным способом. Сообщите о подозрительном письме по утверждённому в вашей компании каналу.'],
    caveat: 'Это общий учебный фрагмент. Перед публикацией эксперт компании уточняет правила и канал сообщения об инцидентах.',
    question: '2. Проверка понимания', prompt: 'Что сделать с неожиданным письмом, которое требует ввести рабочий пароль?',
    options: ['Перейти по ссылке, если имя отправителя знакомо.', 'Не открывать ссылку; проверить запрос через привычный рабочий канал.', 'Ответить на письмо и попросить подтвердить, что оно настоящее.'],
    check: 'Проверить ответ', retry: 'Ответить заново',
    correct: 'Верно. Имя отправителя можно подделать. Для проверки нужен независимый рабочий канал.',
    incorrect: 'Этот вариант не защищает от поддельного отправителя. Не переходите по ссылке и проверьте запрос через независимый рабочий канал.',
    local: 'Ваш ответ остаётся только на этой странице. В журнал компании он не записывается.',
    results: '3. Что видит ответственный за обучение',
    resultNote: 'Ниже — отдельный вымышленный пример журнала. Это не результаты вашего ответа и не данные клиентов.',
    employee: 'Сотрудник', result: 'Учебный результат', action: 'Следующий шаг',
    rows: [
      { person: 'Сотрудник А', status: 'Завершил', score: '9 из 10 · порог 8', action: 'Разобрать результат', detail: 'В рабочем журнале можно проверить результат теста и историю прохождения. Успешный тест сам по себе не подтверждает профессиональную компетентность.' },
      { person: 'Сотрудник Б', status: 'Не сдал тест', score: '6 из 10 · порог 8', action: 'Разобрать ошибку', detail: 'В этом примере сотрудник ошибся в теме подозрительных писем. Ответственный разбирает правило с сотрудником и определяет дальнейшее обучение. Здесь повторный курс не назначается.' },
      { person: 'Сотрудник В', status: 'Просрочил', score: 'Срок истёк · тест не пройден', action: 'Разобрать просрочку', detail: 'В рабочем журнале просроченные назначения доступны через фильтр. Ответственный выясняет причину и при необходимости настраивает напоминание. Здесь письма не отправляются.' },
    ],
    start: 'Как запустить обучение у себя',
    paths: [{ title: 'Есть документы', body: 'Выбираете материалы. Kamilya готовит черновик курса и теста.' }, { title: 'Документов пока нет', body: 'Выбираете доступную основу курса и уточняете правила вашей компании.' }],
    responsibility: 'В обоих случаях эксперт компании проверяет содержание и утверждает публикацию. Отдельный штатный методист для такой проверки не обязателен. Участие специалиста Kamilya и объём сопровождения согласуются отдельно.',
    trial: 'Создать рабочий кабинет', demo: 'Открыть демо-кабинет', login: 'Войти',
  },
  kk: {
    label: 'Оқу мысалы · ойдан шығарылған деректер',
    title: 'Кімге қосымша оқу қажет?',
    intro: 'Сабақ үзіндісін оқып, сұраққа жауап беріңіз және қызметкерлердің нәтижелерін қараңыз. Құжаттар мен тіркелу қажет емес.',
    lesson: '1. Сабақ үзіндісі', course: 'Ақпараттық қауіпсіздік',
    lessonTitle: 'Аккаунтқа кіруді сұрайтын күтпеген хат',
    paragraphs: ['Хатта сілтеме арқылы құпиясөзді шұғыл растау сұралған. Жіберушінің таныс аты хаттың қауіпсіз екенін дәлелдемейді.', 'Сілтемені ашпаңыз және хатқа жауап бермеңіз. Жұмыс сервисіне әдеттегі жолмен кіріңіз. Күдікті хат туралы компанияңыз бекіткен арна арқылы хабарлаңыз.'],
    caveat: 'Бұл — жалпы оқу үзіндісі. Жариялау алдында компания сарапшысы ережелер мен оқиғалар туралы хабарлау арнасын нақтылайды.',
    question: '2. Түсінуді тексеру', prompt: 'Жұмыс құпиясөзін енгізуді талап ететін күтпеген хат келсе, не істеу керек?',
    options: ['Жіберушінің аты таныс болса, сілтемеге өту.', 'Сілтемені ашпау; сұрауды әдеттегі жұмыс арнасы арқылы тексеру.', 'Хатқа жауап беріп, оның шынайы екенін растауды сұрау.'],
    check: 'Жауапты тексеру', retry: 'Қайта жауап беру',
    correct: 'Дұрыс. Жіберушінің атын қолдан жасауға болады. Тексеру үшін бөлек жұмыс арнасын пайдалану қажет.',
    incorrect: 'Бұл нұсқа жалған жіберушіден қорғамайды. Сілтемеге өтпей, сұрауды бөлек жұмыс арнасы арқылы тексеріңіз.',
    local: 'Жауабыңыз тек осы бетте қалады. Компания журналына жазылмайды.',
    results: '3. Оқуға жауапты маман не көреді',
    resultNote: 'Төменде журналдың бөлек, ойдан шығарылған мысалы берілген. Бұл сіздің жауабыңыздың нәтижесі де, клиент деректері де емес.',
    employee: 'Қызметкер', result: 'Оқу нәтижесі', action: 'Келесі қадам',
    rows: [
      { person: 'А қызметкері', status: 'Аяқтады', score: '10-нан 9 · өту шегі 8', action: 'Нәтижені талдау', detail: 'Жұмыс журналында тест нәтижесі мен оқу тарихын тексеруге болады. Тесттен сәтті өту кәсіби құзыреттілікті өздігінен растамайды.' },
      { person: 'Б қызметкері', status: 'Тесттен өтпеді', score: '10-нан 6 · өту шегі 8', action: 'Қатені талдау', detail: 'Бұл мысалда қызметкер күдікті хаттар тақырыбында қателесті. Жауапты маман ережені қызметкермен талқылап, әрі қарайғы оқуды анықтайды. Мұнда қайталау курсы тағайындалмайды.' },
      { person: 'В қызметкері', status: 'Мерзімі өтті', score: 'Мерзімі аяқталды · тест тапсырылмаған', action: 'Кешігуді талдау', detail: 'Жұмыс журналында мерзімі өткен тапсырмаларды сүзгі арқылы табуға болады. Жауапты маман себебін анықтап, қажет болса еске салуды баптайды. Мұнда хаттар жіберілмейді.' },
    ],
    start: 'Компанияңызда оқуды қалай бастауға болады',
    paths: [{ title: 'Құжаттар бар', body: 'Материалдарды таңдайсыз. Kamilya курс пен тестің бастапқы нұсқасын дайындайды.' }, { title: 'Құжаттар әзірге жоқ', body: 'Қолжетімді курс негізін таңдап, компанияңыздың ережелерін нақтылайсыз.' }],
    responsibility: 'Екі жағдайда да компания сарапшысы мазмұнды тексеріп, жариялауды мақұлдайды. Бұл үшін штатта жеке әдіскер болуы міндетті емес. Kamilya маманының қатысуы мен сүйемелдеу көлемі бөлек келісіледі.',
    trial: 'Жұмыс кабинетін ашу', demo: 'Демо-кабинетті ашу', login: 'Кіру',
  },
  en: {
    label: 'Learning example · fictional data', title: 'Who needs further training?',
    intro: 'Read a lesson excerpt, answer a question and explore employee outcomes. No documents or registration required.',
    lesson: '1. Lesson excerpt', course: 'Information security', lessonTitle: 'An unexpected email asking you to sign in',
    paragraphs: ['An email asks you to confirm your password urgently using a link. A familiar sender name does not prove the message is safe.', 'Do not open the link or reply. Open the work service through your usual route. Report the suspicious message through the channel approved by your company.'],
    caveat: 'This is a general learning excerpt. Before publication, a company expert confirms the rules and incident reporting channel.',
    question: '2. Check understanding', prompt: 'What should you do with an unexpected email requesting your work password?',
    options: ['Follow the link if the sender name is familiar.', 'Do not open the link; verify through your usual work channel.', 'Reply asking the sender to confirm the message is genuine.'],
    check: 'Check answer', retry: 'Try again', correct: 'Correct. Sender names can be spoofed. Use an independent work channel to verify.',
    incorrect: 'This option does not protect against an impersonated sender. Avoid the link and verify through an independent work channel.',
    local: 'Your answer stays on this page only. It is not recorded in a company log.',
    results: '3. What the training owner sees', resultNote: 'This is a separate fictional log example, not the result of your answer or customer data.',
    employee: 'Employee', result: 'Learning outcome', action: 'Next step',
    rows: [
      { person: 'Employee A', status: 'Completed', score: '9 of 10 · pass mark 8', action: 'Explore result', detail: 'In the working log, the owner can review the score and learning history. Passing a test alone does not establish professional competence.' },
      { person: 'Employee B', status: 'Did not pass', score: '6 of 10 · pass mark 8', action: 'Explore mistake', detail: 'In this example, the employee missed the suspicious-email topic. The owner discusses the rule and decides on further learning. No repeat course is assigned here.' },
      { person: 'Employee C', status: 'Overdue', score: 'Deadline passed · test not taken', action: 'Explore overdue task', detail: 'The working log offers an overdue filter. The owner checks the reason and can configure a reminder where needed. No emails are sent here.' },
    ],
    start: 'Starting in your company', paths: [{ title: 'You have documents', body: 'Choose your materials. Kamilya prepares a draft course and test.' }, { title: 'No documents yet', body: 'Choose an available course basis and clarify your company rules.' }],
    responsibility: 'In both cases, a company expert checks the content and approves publication. A dedicated staff methodologist is not required for that review. Kamilya specialist involvement and support scope are agreed separately.',
    trial: 'Create a work account', demo: 'Open demo workspace', login: 'Sign in',
  },
};

export type ExampleLanguage = keyof typeof exampleCopy;
export function resolveExampleLanguage(value: unknown): ExampleLanguage {
  return value === 'kk' || value === 'en' ? value : 'ru';
}
