'use client';

import { useState } from 'react';
import { Button, Card, CardContent, Badge } from '@/components/ui';
import { cancelApprovalRequest, revokeApprovalAccess, resendApprovalDelivery, type ApprovalRequestSummary } from '@/lib/courseApproval';
import { toast } from '@/components/ui/Toast';

export function ApprovalStatusPanel({ requests, onRefresh }: { requests: ApprovalRequestSummary[]; onRefresh?: () => void }) {
  const [busyId, setBusyId] = useState<string | null>(null);
  async function action(requestId: string, kind: 'cancel' | 'revoke' | 'resend') {
    setBusyId(requestId);
    try { if (kind === 'cancel') await cancelApprovalRequest(requestId); else if (kind === 'revoke') await revokeApprovalAccess(requestId); else await resendApprovalDelivery(requestId); onRefresh?.(); toast.success(kind === 'cancel' ? 'Запрос отменён' : kind === 'revoke' ? 'Доступ отозван' : 'Доставка повторена'); }
    catch { toast.error('Операция не выполнена'); }
    finally { setBusyId(null); }
  }
  if (requests.length === 0) return <Card><CardContent className="p-5 text-sm text-muted-foreground">Активных запросов на согласование нет.</CardContent></Card>;
  return <div className="space-y-3">{requests.map((request) => <Card key={request.request_id}><CardContent className="space-y-3 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Запрос {request.request_id.slice(0, 8)}</h3><p className="break-all text-xs text-muted-foreground">Ревизия {request.revision_number ? `#${request.revision_number}` : request.revision_id}{request.snapshot_sha256 ? ` · SHA-256 ${request.snapshot_sha256}` : ''}</p></div><Badge variant={request.outcome === 'approved' ? 'default' : 'outline'}>{request.outcome === 'changes_requested' ? 'Нужны изменения' : request.outcome === 'approved' ? 'Согласован' : request.outcome === 'cancelled' ? 'Отменён' : 'Ожидает решения'}</Badge></div><div className="grid gap-2 text-sm sm:grid-cols-3"><span>Канал: {request.delivery_mode === 'email' ? 'Email' : 'Ссылка + PIN'}</span><span>Рецензентов: {request.reviewer_ids?.length ?? request.reviewer_count ?? request.reviewers?.length ?? request.work_items?.length ?? '—'}</span><span>Дедлайн: {request.due_at ? new Date(request.due_at).toLocaleString('ru-RU') : 'Не задан'}</span></div>{(request.reviewers || request.work_items) && <div className="overflow-x-auto rounded border"><table className="min-w-[620px] w-full text-left text-xs"><caption className="sr-only">Статус рецензентов</caption><thead><tr className="border-b text-muted-foreground"><th className="p-2">Рецензент</th><th className="p-2">Доставка</th><th className="p-2">Доступ</th><th className="p-2">Активность</th><th className="p-2">Прогресс</th><th className="p-2">Результат</th></tr></thead><tbody>{(request.work_items || request.reviewers || []).map((reviewer) => <tr key={reviewer.reviewer_id || reviewer.id || reviewer.decision_at} className="border-b last:border-0"><td className="p-2 break-all">{reviewer.reviewer_id || reviewer.id || '—'}</td><td className="p-2">{reviewer.delivery_state || request.deliveries?.[0]?.status || '—'}</td><td className="p-2">{reviewer.access_state || '—'}</td><td className="p-2">{reviewer.activity_state || '—'}</td><td className="p-2">{reviewer.progress == null ? '—' : `${reviewer.progress}%`} · {reviewer.deadline_state || '—'}</td><td className="p-2">{reviewer.outcome || reviewer.decision || 'pending'}</td></tr>)}</tbody></table></div>}<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busyId === request.request_id || request.outcome !== 'pending'} onClick={() => void action(request.request_id, 'cancel')}>Отменить запрос</Button><Button size="sm" variant="outline" disabled={busyId === request.request_id} onClick={() => void action(request.request_id, 'resend')}>Повторить доставку</Button><Button size="sm" variant="outline" disabled={busyId === request.request_id} onClick={() => void action(request.request_id, 'revoke')}>Отозвать доступ</Button></div></CardContent></Card>)}</div>;
}
