import type { AppRole } from '@/lib/routeRegistry';

export type HelpLocale = 'ru' | 'kk' | 'en';

interface LocalizedText {
  ru: string;
  kk: string;
  en: string;
}

interface HelpTopicDefinition {
  id: string;
  paths: readonly string[];
  roles: readonly AppRole[];
  title: LocalizedText;
  purpose: LocalizedText;
  steps: readonly LocalizedText[];
  example: LocalizedText;
  result: LocalizedText;
  important: LocalizedText;
}

export interface ContextualHelpContent {
  id: string;
  title: string;
  purpose: string;
  steps: string[];
  example: string;
  result: string;
  important: string;
}

const text = (ru: string, kk: string, en: string): LocalizedText => ({ ru, kk, en });
const topic = (
  id: string,
  paths: readonly string[],
  roles: readonly AppRole[],
  title: LocalizedText,
  purpose: LocalizedText,
  steps: readonly LocalizedText[],
  example: LocalizedText,
  result: LocalizedText,
  important: LocalizedText,
): HelpTopicDefinition => ({ id, paths, roles, title, purpose, steps, example, result, important });

const TOPICS: readonly HelpTopicDefinition[] = [
  {
    id: 'methodologist-dashboard', paths: ['/dashboard'], roles: ['methodologist'],
    title: text('Обзор обучения', 'Оқу шолуы', 'Learning overview'),
    purpose: text('Краткая картина текущего обучения: что требует внимания, какие курсы и назначения активны.', 'Ағымдағы оқытудың қысқаша көрінісі: назарды не қажет етеді, қандай курстар мен тағайындаулар белсенді.', 'A concise view of current learning activity, active courses, assignments, and items needing attention.'),
    steps: [text('Проверьте показатели и предупреждения.', 'Көрсеткіштер мен ескертулерді тексеріңіз.', 'Review indicators and warnings.'), text('Откройте нужный объект из карточки.', 'Карточкадан қажетті нысанды ашыңыз.', 'Open the relevant item from its card.'), text('После действия вернитесь и убедитесь, что показатель обновился.', 'Әрекеттен кейін көрсеткіштің жаңарғанын тексеріңіз.', 'Return after the action and confirm the indicator changed.')],
    example: text('Если есть просроченные назначения, откройте их список и уточните срок или получателей.', 'Мерзімі өткен тағайындаулар болса, тізімді ашып, мерзімін немесе алушыларын нақтылаңыз.', 'If assignments are overdue, open the list and review the deadline or recipients.'),
    result: text('Вы понимаете, что делать следующим шагом.', 'Келесі қадамды түсінесіз.', 'You know the next operational action.'),
    important: text('Панель показывает состояние, но не заменяет проверку самого курса или назначения.', 'Панель күйді көрсетеді, бірақ курс не тағайындауды тексеруді алмастырмайды.', 'The dashboard summarizes state; it does not replace checking the course or assignment itself.'),
  },
  {
    id: 'ai-generation', paths: ['/ai/generate'], roles: ['methodologist'],
    title: text('Создать курс из материалов', 'Материалдардан курс жасау', 'Create course from materials'),
    purpose: text('Создание черновика курса из ваших документов и требований.', 'Құжаттарыңыз бен талаптарыңыздан курс жобасын жасау.', 'Create a draft course from your documents and requirements.'),
    steps: [text('Выберите проверенные исходные документы.', 'Тексерілген бастапқы құжаттарды таңдаңыз.', 'Choose verified source documents.'), text('Укажите аудиторию, цель и ограничения курса.', 'Аудиторияны, мақсатты және шектеулерді көрсетіңіз.', 'Specify the audience, objective, and constraints.'), text('Проверьте каждое утверждение и сохраните только как черновик до методической проверки.', 'Әр тұжырымды тексеріп, әдістемелік тексеруге дейін жоба ретінде сақтаңыз.', 'Verify every claim and keep the result as a draft until methodological review.')],
    example: text('Загрузите инструкцию по работе с кассой и попросите подготовить вводный курс для нового кассира.', 'Касса нұсқаулығын жүктеп, жаңа кассирге кіріспе курс дайындауды сұраңыз.', 'Upload a cash-desk procedure and request an introductory course for a new cashier.'),
    result: text('Появится редактируемый черновик, а не автоматически утверждённый курс.', 'Автоматты бекітілген курс емес, өңделетін жоба пайда болады.', 'You receive an editable draft, not an automatically approved course.'),
    important: text('AI может ошибаться. Ответственность за итоговый материал остаётся у методиста.', 'AI қателесуі мүмкін. Соңғы материалға әдіскер жауап береді.', 'AI can be wrong. The methodologist remains responsible for the final material.'),
  },
  {
    id: 'courses', paths: ['/courses'], roles: ['methodologist'],
    title: text('Курсы', 'Курстар', 'Courses'),
    purpose: text('Подготовка, проверка, публикация и обновление учебных материалов.', 'Оқу материалдарын дайындау, тексеру, жариялау және жаңарту.', 'Prepare, review, publish, and update learning content.'),
    steps: [text('Создайте курс или откройте черновик.', 'Курс жасаңыз немесе жобаны ашыңыз.', 'Create a course or open a draft.'), text('Проверьте содержание, тест и обязательные сведения.', 'Мазмұнды, тестті және міндетті мәліметтерді тексеріңіз.', 'Review content, assessment, and required details.'), text('Публикуйте только готовую версию, затем назначьте её сотрудникам.', 'Дайын нұсқаны ғана жариялап, қызметкерлерге тағайындаңыз.', 'Publish only the approved version, then assign it to employees.')],
    example: text('Курс «Вводный инструктаж» сначала проверяется ответственным, затем публикуется и назначается новичкам.', '«Кіріспе нұсқама» курсы алдымен тексеріліп, кейін жарияланып, жаңа қызметкерлерге тағайындалады.', 'An induction course is reviewed first, then published and assigned to new hires.'),
    result: text('Готовая управляемая версия курса с историей изменений.', 'Өзгерістер тарихы бар басқарылатын курс нұсқасы.', 'A controlled course version with change history.'),
    important: text('Черновик недоступен обучающимся, а изменение опубликованного курса требует повторной проверки.', 'Жоба оқушыларға қолжетімсіз; жарияланған курсты өзгерту қайта тексеруді қажет етеді.', 'Learners cannot see drafts, and published-course changes require another review.'),
  },
  {
    id: 'quizzes', paths: ['/quizzes'], roles: ['methodologist'],
    title: text('Тесты и вопросы', 'Тесттер мен сұрақтар', 'Tests and questions'),
    purpose: text('Проверка знаний по материалам курса с понятными критериями прохождения.', 'Курс материалдары бойынша білімді түсінікті өту талаптарымен тексеру.', 'Assess knowledge with clear passing criteria.'),
    steps: [text('Выберите курс и темы проверки.', 'Курс пен тексеру тақырыптарын таңдаңыз.', 'Choose the course and assessment topics.'), text('Добавьте однозначные вопросы и отметьте правильные ответы.', 'Нақты сұрақтар қосып, дұрыс жауаптарды белгілеңіз.', 'Add unambiguous questions and mark correct answers.'), text('Настройте проходной балл и проверьте тест как обучающийся.', 'Өту балын баптап, тестті оқушы ретінде тексеріңіз.', 'Set the passing score and preview the quiz as a learner.')],
    example: text('После курса по ИБ сотрудник отвечает на 10 вопросов и проходит при 8 правильных ответах.', 'ИБ курсынан кейін қызметкер 10 сұраққа жауап беріп, 8 дұрыс жауаппен өтеді.', 'After an information-security course, a learner passes with 8 correct answers out of 10.'),
    result: text('Тест, который можно связать с курсом и учитывать в результате обучения.', 'Курспен байланыстырып, оқу нәтижесінде есепке алуға болатын тест.', 'A quiz that can be linked to a course and included in learning results.'),
    important: text('Не используйте вопросы с несколькими трактовками и ответы, которых нет в материале.', 'Екіұшты сұрақтар мен материалда жоқ жауаптарды қолданбаңыз.', 'Avoid ambiguous questions and answers not supported by the learning material.'),
  },
  {
    id: 'documents', paths: ['/documents'], roles: ['methodologist'],
    title: text('Документы', 'Құжаттар', 'Documents'),
    purpose: text('Хранение утверждённых источников, из которых создаются и обновляются курсы.', 'Курстар жасалатын және жаңартылатын бекітілген дереккөздерді сақтау.', 'Store approved source documents used to create and update courses.'),
    steps: [text('Загрузите документ, затем откройте сведения об актуальности источника.', 'Құжатты жүктеп, дереккөздің өзектілігі туралы мәліметті ашыңыз.', 'Upload the document, then open its source-actuality details.'), text('После загрузки проверьте отображаемую версию, задайте владельца и даты проверки в сведениях источника.', 'Жүктегеннен кейін көрсетілген нұсқаны тексеріп, дереккөз мәліметінде иесін және тексеру күндерін көрсетіңіз.', 'After upload, check the displayed version and set the owner and review dates in the source details.'), text('При появлении новой проиндексированной версии сравните её и проверьте связанные курсы.', 'Жаңа индекстелген нұсқа шыққанда оны салыстырып, байланысты курстарды тексеріңіз.', 'When a new indexed version appears, compare it and review linked courses.')],
    example: text('«Регламент кассовых операций, версия 3 от 01.08.2026» используется для курса кассиров.', '«Кассалық операциялар регламенті, 01.08.2026 күнгі 3-нұсқа» кассирлер курсына қолданылады.', '“Cash operations procedure, version 3 dated 1 Aug 2026” is linked to the cashier course.'),
    result: text('Понятно, на каком документе основан каждый курс.', 'Әр курстың қай құжатқа негізделгені түсінікті.', 'Each course has a traceable source.'),
    important: text('Не загружайте личные данные и документы без права использования.', 'Жеке деректерді және пайдалануға құқығы жоқ құжаттарды жүктемеңіз.', 'Do not upload personal data or documents you are not authorized to use.'),
  },
  {
    id: 'learning-paths', paths: ['/learning-paths'], roles: ['methodologist'],
    title: text('Программы обучения', 'Оқу бағдарламалары', 'Learning programs'),
    purpose: text('Последовательность нескольких курсов для роли, адаптации или обязательной подготовки.', 'Рөлге, бейімделуге немесе міндетті даярлыққа арналған бірнеше курстың реті.', 'An ordered set of courses for a role, onboarding, or required training.'),
    steps: [text('Определите цель и группу сотрудников.', 'Мақсат пен қызметкерлер тобын анықтаңыз.', 'Define the objective and employee group.'), text('Добавьте курсы в нужном порядке и задайте сроки.', 'Курстарды ретімен қосып, мерзімдерін белгілеңіз.', 'Add courses in order and set deadlines.'), text('Проверьте маршрут целиком и только затем назначайте.', 'Маршрутты толық тексеріп, содан кейін ғана тағайындаңыз.', 'Review the entire path before assigning it.')],
    example: text('Программа нового кассира: знакомство с компанией → кассовые операции → ИБ → итоговый тест.', 'Жаңа кассир бағдарламасы: компаниямен танысу → кассалық операциялар → ИБ → қорытынды тест.', 'New cashier program: company introduction → cash operations → information security → final quiz.'),
    result: text('Сотрудник получает понятный маршрут, а руководитель видит общий прогресс.', 'Қызметкер түсінікті маршрут алады, басшы жалпы прогресті көреді.', 'The learner gets a clear path and the manager sees overall progress.'),
    important: text('Программа не заменяет отдельные курсы: сначала подготовьте и опубликуйте их.', 'Бағдарлама жеке курстарды алмастырмайды: алдымен оларды дайындап, жариялаңыз.', 'A program does not replace its courses; prepare and publish them first.'),
  },
  {
    id: 'learning-cycles', paths: ['/learning-cycles'], roles: ['methodologist'],
    title: text('Циклы обучения', 'Оқу циклдері', 'Learning cycles'),
    purpose: text('Повторное назначение курса или программы одному сотруднику через заданный интервал.', 'Белгіленген аралықтан кейін курс немесе бағдарламаны бір қызметкерге қайта тағайындау.', 'Reassign a course or program to one employee on a defined schedule.'),
    steps: [text('Для курса выберите опубликованный курс и сотрудника.', 'Курс үшін жарияланған курс пен қызметкерді таңдаңыз.', 'For a course, choose the published course and employee.'), text('Для курса задайте интервал повторения и срок прохождения нового периода; периодичность программы настраивается в самой программе обучения.', 'Курс үшін қайталау аралығы мен жаңа кезеңді аяқтау мерзімін белгілеңіз; бағдарлама мерзімділігі оқу бағдарламасының өзінде бапталады.', 'For a course, set the recurrence interval and completion window; program recurrence is configured in the learning program itself.'), text('Создайте правило, проверьте его и только затем активируйте.', 'Ережені жасап, тексеріп, содан кейін ғана іске қосыңыз.', 'Create the rule, review it, and only then activate it.')],
    example: text('Курс по безопасности назначается повторно каждые 365 дней, а на прохождение нового периода даётся 30 дней.', 'Қауіпсіздік курсы әр 365 күн сайын қайта тағайындалады, жаңа кезеңді аяқтауға 30 күн беріледі.', 'A safety course is reassigned every 365 days, with 30 days to complete each new period.'),
    result: text('Каждый запуск создаёт отдельный период обучения со своим прогрессом и сроком.', 'Әр іске қосу жеке ілгерілеуі мен мерзімі бар жаңа оқу кезеңін жасайды.', 'Each run creates a separate learning period with its own progress and due date.'),
    important: text('Интервал определяет частоту повторения, а срок выполнения — сколько дней дано сотруднику внутри каждого периода.', 'Аралық қайталау жиілігін, ал орындау мерзімі әр кезеңде қызметкерге берілетін күн санын анықтайды.', 'The interval controls recurrence; the completion window is the time allowed within each period.'),
  },
  {
    id: 'cohorts', paths: ['/cohorts'], roles: ['methodologist'],
    title: text('Группы сотрудников', 'Қызметкерлер топтары', 'Employee groups'),
    purpose: text('Объединение сотрудников для общего назначения и контроля.', 'Қызметкерлерді ортақ тағайындау және бақылау үшін біріктіру.', 'Group employees for shared assignment and monitoring.'),
    steps: [text('Создайте группу с понятным критерием.', 'Түсінікті өлшеммен топ жасаңыз.', 'Create a group with a clear criterion.'), text('Добавьте нужных сотрудников и проверьте состав.', 'Қажетті қызметкерлерді қосып, құрамын тексеріңіз.', 'Add employees and verify membership.'), text('Используйте группу как аудиторию в программе обучения или примените к ней правило обучения.', 'Топты оқу бағдарламасында аудитория ретінде пайдаланыңыз немесе оған оқу ережесін қолданыңыз.', 'Use the group as a learning-program audience or apply a training rule to it.')],
    example: text('Группа «Новые сотрудники — август» получает общую программу адаптации.', '«Тамыздағы жаңа қызметкерлер» тобы ортақ бейімделу бағдарламасын алады.', 'The “August new hires” group receives one onboarding program.'),
    result: text('Меньше ручных назначений и единый контроль группы.', 'Қолмен тағайындау азайып, топ бірыңғай бақыланады.', 'Fewer manual assignments and consistent group tracking.'),
    important: text('Перед назначением проверьте, что в группе нет лишних сотрудников.', 'Тағайындаудан бұрын топта артық қызметкерлер жоқ екенін тексеріңіз.', 'Before assigning, ensure the group contains only intended employees.'),
  },
  {
    id: 'staff', paths: ['/staff'], roles: ['methodologist'],
    title: text('Сотрудники и структура', 'Қызметкерлер және құрылым', 'Employees and structure'),
    purpose: text('Ведение филиалов, отделов, должностей и сотрудников компании.', 'Компания филиалдарын, бөлімдерін, лауазымдарын және қызметкерлерін жүргізу.', 'Manage branches, departments, positions, and employees.'),
    steps: [text('Сначала создайте филиалы и вложенные отделы.', 'Алдымен филиалдар мен ішкі бөлімдерді жасаңыз.', 'Create branches and nested departments first.'), text('Добавьте должности в нужные подразделения.', 'Лауазымдарды тиісті бөлімдерге қосыңыз.', 'Add positions to the correct units.'), text('Импортируйте или добавьте сотрудников и проверьте результат до назначения обучения.', 'Қызметкерлерді импорттап не қосып, оқу тағайындамас бұрын нәтижені тексеріңіз.', 'Import or add employees and verify the result before assigning learning.')],
    example: text('Филиал Павлодар → Операционный отдел → Кассир → сотрудник с табельным номером.', 'Павлодар филиалы → Операциялық бөлім → Кассир → табельдік нөмірі бар қызметкер.', 'Pavlodar branch → Operations department → Cashier → employee with personnel number.'),
    result: text('Организационная структура, на которую можно назначать правила и обучение.', 'Ережелер мен оқуды тағайындауға болатын ұйымдық құрылым.', 'An organization structure that can receive rules and learning assignments.'),
    important: text('Филиал и отдел — разные уровни. Перед импортом проверяйте предложение системы, а не применяйте файл вслепую.', 'Филиал мен бөлім — әртүрлі деңгей. Импорт алдында жүйе ұсынысын тексеріңіз.', 'A branch and a department are different levels. Review the proposed import before applying it.'),
  },
  {
    id: 'training-procedures', paths: ['/training-procedures'], roles: ['methodologist'],
    title: text('Подтверждение обучения', 'Оқытуды растау', 'Training confirmation'),
    purpose: text('Настройка черновика процедуры: ознакомление, внутренняя аттестация или отдельное решение о допуске.', 'Танысу, ішкі аттестаттау немесе жұмысқа жіберу туралы бөлек шешім рәсімінің жобасын баптау.', 'Configure a draft procedure for acknowledgement, internal attestation, or a separate admission decision.'),
    steps: [text('Выберите понятный тип процедуры.', 'Түсінікті рәсім түрін таңдаңыз.', 'Choose a clear procedure type.'), text('Заполните только применимые обязательные сведения.', 'Тек қолданылатын міндетті мәліметтерді толтырыңыз.', 'Complete only applicable required details.'), text('Согласуйте процедуру с ответственным и сохраните реквизиты утверждения.', 'Рәсімді жауапты тұлғамен келісіп, бекіту деректерін сақтаңыз.', 'Agree the procedure with its owner and record approval details.')],
    example: text('Для ознакомления настройте тип процедуры и способ подтверждения; сохранение настройки ещё не фиксирует, что сотрудник прочитал документ.', 'Танысу үшін рәсім түрі мен растау тәсілін баптаңыз; баптауды сақтау қызметкердің құжатты оқығанын әлі тіркемейді.', 'For acknowledgement, configure the procedure type and confirmation method; saving the setup does not record that an employee read the document.'),
    result: text('Сохраняется понятная настройка процедуры и её оснований для последующего отдельного процесса.', 'Кейінгі бөлек процесс үшін рәсімнің түсінікті баптауы мен негіздері сақталады.', 'A clear procedure setup and its bases are saved for a later separate process.'),
    important: text('Настройка не подтверждает выполненное действие: OTP подтверждает только одноразовый код и не является ЭЦП, тест не заменяет отдельное решение о допуске.', 'Баптау орындалған әрекетті растамайды: OTP тек бір реттік кодты растайды және ЭЦҚ емес, тест жұмысқа жіберу туралы бөлек шешімді алмастырмайды.', 'Setup does not prove completion: OTP confirms only a one-time code and is not a digital signature; a test does not replace a separate admission decision.'),
  },
  {
    id: 'competencies', paths: ['/competencies'], roles: ['methodologist'],
    title: text('Матрица компетенций', 'Құзыреттер матрицасы', 'Competency matrix'),
    purpose: text('Связь компетенций с должностями и курсами.', 'Құзыреттерді лауазымдармен және курстармен байланыстыру.', 'Link competencies to positions and courses.'),
    steps: [text('Создайте компетенцию с названием и описанием ожидаемого умения.', 'Күтілетін дағдының атауы мен сипаттамасы бар құзырет жасаңыз.', 'Create a competency with a name and description of the expected ability.'), text('Отметьте связанные должности и курсы.', 'Байланысты лауазымдар мен курстарды белгілеңіз.', 'Select the related positions and courses.'), text('Сохраните проверенные связи и убедитесь, что список обновился.', 'Тексерілген байланыстарды сақтап, тізімнің жаңарғанын тексеріңіз.', 'Save the reviewed links and confirm the list updated.')],
    example: text('Компетенция «Клиентоориентированность» связана с должностью кассира и курсом обслуживания.', '«Клиентке бағдарлану» құзыреті кассир лауазымымен және қызмет көрсету курсымен байланысты.', 'The “Customer focus” competency is linked to the cashier position and a service course.'),
    result: text('В матрице видны связанные должности и курсы.', 'Матрицада байланысты лауазымдар мен курстар көрінеді.', 'The matrix shows the linked positions and courses.'),
    important: text('Матрица описывает связи и не заменяет проверку фактического обучения или готовности сотрудника.', 'Матрица байланыстарды сипаттайды және қызметкердің нақты оқуын не дайындығын тексеруді алмастырмайды.', 'The matrix describes links; it does not replace checking actual learning or employee readiness.'),
  },
  {
    id: 'training-rules', paths: ['/training-rules'], roles: ['methodologist'],
    title: text('Правила обучения', 'Оқу ережелері', 'Training rules'),
    purpose: text('Настройка обязательных опубликованных курсов для организации и отделов.', 'Ұйым мен бөлімдерге міндетті жарияланған курстарды баптау.', 'Configure required published courses for the organization and departments.'),
    steps: [text('Выберите область правила: организацию, отдел или просмотр правил должностей.', 'Ереже ауқымын таңдаңыз: ұйым, бөлім немесе лауазым ережелерін көру.', 'Choose the rule scope: organization, department, or position overview.'), text('Для организации или отдела выберите опубликованный курс и проверьте затронутых сотрудников в предварительном просмотре.', 'Ұйым немесе бөлім үшін жарияланған курсты таңдап, алдын ала қарауда әсер ететін қызметкерлерді тексеріңіз.', 'For an organization or department, choose a published course and review affected employees in the preview.'), text('Подтвердите добавление или удаление только после проверки последствий.', 'Салдарын тексергеннен кейін ғана қосуды немесе жоюды растаңыз.', 'Confirm adding or removing only after reviewing the impact.')],
    example: text('Перед добавлением курса к отделу проверьте число новых назначений и защищённых завершённых назначений.', 'Курс бөлімге қосар алдында жаңа тағайындаулар мен қорғалған аяқталған тағайындаулар санын тексеріңіз.', 'Before attaching a course to a department, review new assignments and protected completed assignments.'),
    result: text('Правило сохраняется после явного подтверждения и применяется к выбранной области.', 'Ереже нақты растаудан кейін сақталып, таңдалған ауқымға қолданылады.', 'The rule is saved after explicit confirmation and applies to the selected scope.'),
    important: text('Предварительный просмотр ничего не меняет; завершённые и назначения из других источников защищены.', 'Алдын ала қарау ештеңені өзгертпейді; аяқталған және басқа дереккөздерден келген тағайындаулар қорғалады.', 'The preview changes nothing; completed assignments and assignments from other sources are protected.'),
  },
  {
    id: 'training-retention', paths: ['/training-retention'], roles: ['methodologist'],
    title: text('Сроки хранения результатов', 'Нәтижелерді сақтау мерзімдері', 'Result retention periods'),
    purpose: text('Просмотр утверждённых сроков хранения результатов и доказательств обучения.', 'Оқу нәтижелері мен дәлелдерін сақтаудың бекітілген мерзімдерін көру.', 'Review approved retention periods for learning results and evidence.'),
    steps: [text('Найдите нужный вид результата или доказательства.', 'Қажетті нәтиже немесе дәлел түрін табыңыз.', 'Find the relevant result or evidence type.'), text('Сверьте срок хранения и указанное основание.', 'Сақтау мерзімі мен көрсетілген негізді салыстырыңыз.', 'Review the retention period and its stated basis.'), text('Если политика отсутствует или требует изменения, обратитесь к администратору Kamilya.', 'Саясат жоқ немесе өзгерту қажет болса, Kamilya әкімшісіне хабарласыңыз.', 'If a policy is missing or needs adjustment, contact the Kamilya administrator.')],
    example: text('Результаты обязательного обучения хранятся 5 лет по внутренней политике организации.', 'Міндетті оқу нәтижелері ұйымның ішкі саясаты бойынша 5 жыл сақталады.', 'Required-training results are retained for five years under company policy.'),
    result: text('Понятно, сколько и на каком основании хранятся результаты обучения.', 'Оқу нәтижелерінің қанша уақыт және қандай негізде сақталатыны түсінікті.', 'You can see how long learning results are retained and on what basis.'),
    important: text('Методист не изменяет политики и не удаляет доказательства из этого раздела.', 'Әдіскер бұл бөлімде саясаттарды өзгертпейді және дәлелдерді жоймайды.', 'A methodologist cannot change policies or delete evidence from this section.'),
  },
  {
    id: 'candidate-assessments', paths: ['/candidate-assessments'], roles: ['methodologist'],
    title: text('Тестирование кандидатов', 'Үміткерлерді тестілеу', 'Candidate testing'),
    purpose: text('Проведение проверки до найма по опубликованному курсу и персональной ссылке.', 'Жұмысқа қабылдауға дейін жарияланған курс пен жеке сілтеме арқылы тексеру жүргізу.', 'Run a pre-hire assessment from a published course using a personal link.'),
    steps: [text('Выберите опубликованный курс с доступным тестом и создайте кампанию.', 'Қолжетімді тесті бар жарияланған курсты таңдап, науқан жасаңыз.', 'Choose a published course with an assessment and create a campaign.'), text('Пригласите кандидата: укажите имя, а email добавьте при необходимости.', 'Үміткерді шақырыңыз: аты-жөнін көрсетіп, қажет болса email қосыңыз.', 'Invite the candidate with a name and, if needed, an email address.'), text('Передайте персональную ссылку и PIN, затем проверьте результат кампании.', 'Жеке сілтеме мен PIN кодын беріп, кейін науқан нәтижесін тексеріңіз.', 'Share the personal link and PIN, then review the campaign result.')],
    example: text('Кандидат на кассира проходит тест по операциям и правилам безопасности.', 'Кассир үміткері операциялар мен қауіпсіздік ережелері бойынша тест өтеді.', 'A cashier candidate completes an operations and safety assessment.'),
    result: text('Сопоставимый результат проверки знаний, а не автоматическое решение о найме.', 'Жұмысқа алу туралы автоматты шешім емес, салыстырмалы білім нәтижесі.', 'A comparable knowledge result, not an automated hiring decision.'),
    important: text('Решение о найме принимает человек; тест — только один из источников.', 'Жұмысқа алу шешімін адам қабылдайды; тест — дереккөздердің бірі ғана.', 'A person makes the hiring decision; the assessment is only one input.'),
  },
  {
    id: 'assignments', paths: ['/assignments'], roles: ['methodologist'],
    title: text('Назначения и доступ', 'Тағайындаулар және қолжетімділік', 'Assignments and access'),
    purpose: text('Выдача сотрудникам опубликованного курса и выбор способа доступа.', 'Қызметкерлерге жарияланған курсты тағайындау және қолжетімділік тәсілін таңдау.', 'Assign a published course to employees and choose how they receive access.'),
    steps: [text('Выберите опубликованный курс и получателей.', 'Жарияланған курс пен алушыларды таңдаңыз.', 'Choose a published course and recipients.'), text('Выберите способ доступа; для персональной ссылки проверьте время после первого входа, срок действия ссылки и при необходимости абсолютный срок «завершить до».', 'Қолжетімділік тәсілін таңдаңыз; жеке сілтеме үшін бірінші кіргеннен кейінгі уақытты, сілтеменің жарамдылық мерзімін және қажет болса «аяқтау керек» абсолютті мерзімін тексеріңіз.', 'Choose the access method; for a personal link, review time after first sign-in, link validity, and, if needed, the absolute “complete by” date.'), text('Создайте назначение и убедитесь, что доступ появился.', 'Тағайындау жасап, қолжетімділік ашылғанын тексеріңіз.', 'Create the assignment and confirm access is available.')],
    example: text('Курс по ИБ назначается всем кассирам двух филиалов до конца недели.', 'ИБ курсы екі филиалдың барлық кассирлеріне апта соңына дейін тағайындалады.', 'An information-security course is assigned to cashiers in two branches by week end.'),
    result: text('У сотрудников появляется обучение, а у методиста — контроль статусов.', 'Қызметкерлерде оқу, әдіскерде мәртебелерді бақылау пайда болады.', 'Learners receive access and the methodologist can track status.'),
    important: text('Перед массовым назначением проверьте выборку получателей на небольшом списке.', 'Жаппай тағайындаудан бұрын алушыларды шағын тізімде тексеріңіз.', 'Before a bulk assignment, validate the recipient selection on a small list.'),
  },
  {
    id: 'mandatory-training', paths: ['/mandatory-training'], roles: ['methodologist'],
    title: text('Обязательное обучение', 'Міндетті оқу', 'Mandatory training'),
    purpose: text('Проверка, что правила обучения превратились в реальные назначения для нужных сотрудников.', 'Оқу ережелерінің қажетті қызметкерлер үшін нақты тағайындауға айналғанын тексеру.', 'Verify that training rules have become real assignments for the right employees.'),
    steps: [text('Сначала разберите строки «Без назначения» и «Требует сверки».', 'Алдымен «Тағайындау жоқ» және «Тексеру қажет» жолдарын қараңыз.', 'Start with Missing assignment and Needs review rows.'), text('Откройте «Почему назначено» и проверьте должность, подразделение или другой источник.', '«Неге тағайындалды» бөлімін ашып, лауазымды, бөлімшені немесе басқа дереккөзді тексеріңіз.', 'Open Why assigned and verify the position, unit, or other source.'), text('После исправления правила проверьте, что состояние обновилось, а ручные назначения сохранились.', 'Ережені түзеткеннен кейін күй жаңарып, қолмен тағайындаулар сақталғанын тексеріңіз.', 'After correcting the rule, confirm the state updates and manual assignments remain intact.')],
    example: text('Правило отдела требует курс, но у нового сотрудника назначение ещё не создано.', 'Бөлім ережесі курсты талап етеді, бірақ жаңа қызметкерге тағайындау әлі жасалмаған.', 'A unit rule requires a course, but the new employee does not yet have an assignment.'),
    result: text('Объяснимая сверка требований и фактических назначений.', 'Талаптар мен нақты тағайындаулардың түсіндірілетін салыстыруы.', 'An explainable reconciliation of requirements and actual assignments.'),
    important: text('Матрица не удаляет ручные и программные назначения: они показываются как защищённые.', 'Матрица қолмен және бағдарлама арқылы тағайындауларды жоймайды: олар қорғалған болып көрсетіледі.', 'The matrix does not delete manual or program assignments; it marks them as protected.'),
  },
  {
    id: 'training-log', paths: ['/training-log'], roles: ['methodologist'],
    title: text('Журнал обучения', 'Оқу журналы', 'Training log'),
    purpose: text('Контроль назначений, прохождения, результатов и подтверждений.', 'Тағайындауларды, өтуді, нәтижелерді және растауларды бақылау.', 'Track assignments, completion, results, and confirmations.'),
    steps: [text('Отфильтруйте по сотруднику, подразделению или курсу.', 'Қызметкер, бөлім немесе курс бойынша сүзгілеңіз.', 'Filter by employee, unit, or course.'), text('Откройте запись и проверьте статус и основание.', 'Жазбаны ашып, мәртебе мен негізді тексеріңіз.', 'Open the record and verify status and basis.'), text('Экспортируйте только необходимый объём для согласованной цели.', 'Келісілген мақсат үшін тек қажетті көлемді экспорттаңыз.', 'Export only what is needed for an approved purpose.')],
    example: text('HR проверяет, кто из сотрудников филиала не завершил обязательный курс.', 'HR филиал қызметкерлерінің қайсысы міндетті курсты аяқтамағанын тексереді.', 'HR checks which branch employees have not completed a required course.'),
    result: text('Проверяемая картина обучения по сотрудникам и программам.', 'Қызметкерлер мен бағдарламалар бойынша тексерілетін оқу көрінісі.', 'A verifiable view of learning by employee and program.'),
    important: text('Журнал содержит служебные данные. Не передавайте выгрузки без рабочей необходимости.', 'Журналда қызметтік деректер бар. Қажетсіз экспорттарды бермеңіз.', 'The log contains operational data. Do not share exports without a business need.'),
  },
  {
    id: 'team', paths: ['/admin/team'], roles: ['admin'],
    title: text('Команда тенанта', 'Тенант командасы', 'Tenant team'),
    purpose: text('Добавление администраторов и методистов, которые управляют кабинетом.', 'Кабинетті басқаратын әкімшілер мен әдіскерлерді қосу.', 'Add administrators and methodologists who manage the tenant.'),
    steps: [text('Укажите корпоративный email, имя и роль.', 'Корпоративтік email, ат және рөлді көрсетіңіз.', 'Enter the corporate email, name, and role.'), text('Оставьте пароль пустым для входа по коду или задайте временный пароль.', 'Кодпен кіру үшін құпиясөзді бос қалдырыңыз немесе уақытша құпиясөз қойыңыз.', 'Leave password blank for email-code sign-in or set a temporary password.'), text('Проверьте сообщение об отправке инструкции и попросите пользователя войти.', 'Нұсқаулық жіберілгені туралы хабарды тексеріп, пайдаланушыдан кіруді сұраңыз.', 'Check the delivery message and ask the user to sign in.')],
    example: text('HR-методист добавляется без пароля и получает письмо со ссылкой на вход по коду.', 'HR-әдіскер құпиясөзсіз қосылып, кодпен кіру сілтемесі бар хат алады.', 'An HR methodologist is added without a password and receives code-first sign-in instructions.'),
    result: text('Активная учётная запись с нужной ролью и понятным способом первого входа.', 'Қажетті рөлі және түсінікті алғашқы кіру тәсілі бар белсенді аккаунт.', 'An active account with the correct role and a clear first sign-in path.'),
    important: text('Не создавайте общий аккаунт на нескольких людей и не передавайте личные пароли.', 'Бірнеше адамға ортақ аккаунт жасамаңыз және жеке құпиясөздерді бермеңіз.', 'Do not share one account among several people or distribute personal passwords.'),
  },
  topic('methodologist-workbench', ['/methodologist-workbench'], ['methodologist'],
    text('Рабочее место методиста', 'Әдіскердің жұмыс орны', 'Methodologist workbench'),
    text('Подготовка назначения курса отделу через команду, предварительный просмотр и явное подтверждение.', 'Курсты бөлімге команда, алдын ала қарау және нақты растау арқылы тағайындауға дайындық.', 'Prepare a course-to-department assignment through a command, preview, and explicit confirmation.'),
    [text('Введите поддерживаемую русскую команду назначения в поле.', 'Өріске қолдау көрсетілетін орысша тағайындау командасын енгізіңіз.', 'Enter a supported Russian assignment command in the field.'), text('Если данных недостаточно или найдено несколько вариантов, уточните курс или отдел и снова откройте предварительный просмотр.', 'Дерек жеткіліксіз немесе бірнеше нұсқа табылса, курс не бөлімді нақтылап, алдын ала қарауды қайта ашыңыз.', 'If details are missing or multiple matches are found, clarify the course or department and request the preview again.'), text('Проверьте предварительный просмотр, подтвердите назначение и сверяйте полученную квитанцию.', 'Алдын ала қарауды тексеріп, тағайындауды растаңыз және алынған түбіртекті салыстырыңыз.', 'Review the preview, confirm the assignment, and check the resulting receipt.')],
    text('Перед подтверждением проверьте курс, отдел, получателей, срок и область действия.', 'Растамас бұрын курс, бөлім, алушылар, мерзім және қолданылу аясын тексеріңіз.', 'Before confirmation, verify the course, department, recipients, due date, and scope.'),
    text('После подтверждения квитанция показывает созданные и пропущенные назначения, а также состояние уведомлений.', 'Растаудан кейін түбіртек жасалған және өткізіліп кеткен тағайындаулар мен хабарландыру күйін көрсетеді.', 'After confirmation, the receipt shows created and skipped assignments and notification state.'),
    text('Доступность этого раздела зависит от включённой функции; он не заменяет канонические страницы.', 'Бұл бөлімнің қолжетімділігі функцияның қосылуына байланысты; ол канондық беттерді алмастырмайды.', 'This section depends on the feature flag and does not replace canonical pages.')),
  topic('positions', ['/positions'], ['methodologist'],
    text('Должности', 'Лауазымдар', 'Positions'),
    text('Просмотр требований к должности и связанных учебных материалов.', 'Лауазым талаптары мен байланысты оқу материалдарын көру.', 'Review position requirements and related learning.'),
    [text('Выберите должность или найдите её в списке.', 'Лауазымды таңдаңыз немесе тізімнен табыңыз.', 'Select or find a position.'), text('Проверьте профиль, инструкцию, компетенции и обучение.', 'Профильді, нұсқаулықты, құзыреттерді және оқуды тексеріңіз.', 'Review the profile, instruction, competencies, and training.'), text('Сохраняйте только проверенные изменения с понятным основанием.', 'Тек негізі түсінікті тексерілген өзгерістерді сақтаңыз.', 'Save only reviewed changes with a clear reason.')],
    text('Для должности «Кассир» проверьте обязательные курсы и уровень компетенций.', '«Кассир» лауазымы үшін міндетті курстар мен құзырет деңгейін тексеріңіз.', 'For a cashier position, review required courses and competency level.'),
    text('Требования должности связаны с сотрудниками и обучением.', 'Лауазым талаптары қызметкерлермен және оқумен байланыстырылған.', 'Position requirements are connected to people and learning.'),
    text('Карточка показывает требования, но не подтверждает фактическую готовность сотрудника без журнала обучения.', 'Карточка талаптарды көрсетеді, бірақ журналсыз қызметкердің нақты дайындығын растамайды.', 'The card shows requirements; the training log is still needed to confirm actual readiness.')),
  topic('profile', ['/profile'], ['admin', 'methodologist', 'student', 'superadmin'],
    text('Мой профиль', 'Менің профилім', 'My profile'),
    text('Проверка личных данных, языка и параметров безопасности аккаунта.', 'Жеке деректерді, тілді және аккаунт қауіпсіздігі параметрлерін тексеру.', 'Review personal details, language, and account security settings.'),
    [text('Проверьте имя и контактные данные.', 'Атыңыз бен байланыс деректерін тексеріңіз.', 'Review your name and contact details.'), text('Выберите язык интерфейса.', 'Интерфейс тілін таңдаңыз.', 'Choose the interface language.'), text('Проверьте доступные настройки безопасности.', 'Қолжетімді қауіпсіздік параметрлерін тексеріңіз.', 'Review available security settings.')],
    text('После смены языка убедитесь, что интерфейс обновился.', 'Тілді өзгерткеннен кейін интерфейс жаңарғанын тексеріңіз.', 'After changing language, confirm the interface updated.'),
    text('Профиль отражает настройки текущего пользователя.', 'Профиль ағымдағы пайдаланушының параметрлерін көрсетеді.', 'The profile reflects the current user’s settings.'),
    text('Профиль не меняет права активной роли и не даёт доступ к чужим данным.', 'Профиль белсенді рөл құқықтарын өзгертпейді және бөтен деректерге жол ашпайды.', 'The profile does not change active-role permissions or expose other users’ data.')),
  topic('student-dashboard', ['/student'], ['student'],
    text('Моё обучение', 'Менің оқуым', 'My learning'),
    text('Точка входа обучающегося к текущему курсу и прогрессу.', 'Оқушының ағымдағы курс пен ілгерілеуге кіру нүктесі.', 'The learner entry point for current courses and progress.'),
    [text('Проверьте следующий доступный курс.', 'Келесі қолжетімді курсты тексеріңіз.', 'Review the next available course.'), text('Откройте курс и продолжите с сохранённого места.', 'Курсты ашып, сақталған жерден жалғастырыңыз.', 'Open the course and continue from the saved place.'), text('После занятия проверьте прогресс и результат.', 'Сабақтан кейін ілгерілеу мен нәтижені тексеріңіз.', 'After learning, check progress and the result.')],
    text('Если курс заблокирован, сначала завершите обязательный предыдущий шаг.', 'Курс бұғатталса, алдымен міндетті алдыңғы қадамды аяқтаңыз.', 'If a course is locked, complete the required prior step first.'),
    text('Видимый прогресс и понятный следующий шаг.', 'Көрінетін ілгерілеу және түсінікті келесі қадам.', 'Visible progress and a clear next step.'),
    text('Доступ зависит от назначений; обзор не создаёт и не изменяет их.', 'Қолжетімділік тағайындауларға байланысты; шолу оларды жасамайды және өзгертпейді.', 'Access depends on assignments; the overview does not create or change them.')),
  topic('student-my-courses', ['/my-courses'], ['student'],
    text('Мои курсы', 'Менің курстарым', 'My courses'),
    text('Список назначенных курсов и переход к обучению.', 'Тағайындалған курстар тізімі және оқуға өту.', 'View assigned courses and open learning.'),
    [text('Выберите курс из списка.', 'Тізімнен курсты таңдаңыз.', 'Choose a course from the list.'), text('Откройте доступный курс.', 'Қолжетімді курсты ашыңыз.', 'Open an available course.'), text('Проверьте статус после занятия.', 'Сабақтан кейін мәртебені тексеріңіз.', 'Check status after learning.')],
    text('Завершённый курс остаётся доступным для повторного просмотра, если это разрешено.', 'Аяқталған курс рұқсат етілсе, қайта қарауға қолжетімді болып қалады.', 'A completed course may remain available for review when allowed.'),
    text('Курс открывается из единого списка назначений.', 'Курс тағайындаулардың бірыңғай тізімінен ашылады.', 'Courses open from one assignment list.'),
    text('Нет доступного курса — это состояние назначений, а не ошибка профиля.', 'Қолжетімді курс жоқ болса, бұл профиль қатесі емес, тағайындау күйі.', 'No available course reflects assignment state, not a profile error.')),
  topic('student-my-quizzes', ['/my-quizzes'], ['student'],
    text('Мои тесты', 'Менің тесттерім', 'My quizzes'),
    text('Переход к назначенным и завершённым проверкам знаний.', 'Тағайындалған және аяқталған білім тексерулеріне өту.', 'Open assigned and completed knowledge checks.'),
    [text('Откройте тест, который можно пройти.', 'Өтуге болатын тестті ашыңыз.', 'Open a quiz that is available.'), text('Ответьте на вопросы и отправьте попытку.', 'Сұрақтарға жауап беріп, әрекетті жіберіңіз.', 'Answer the questions and submit the attempt.'), text('Проверьте итоговый статус.', 'Қорытынды мәртебені тексеріңіз.', 'Review the final status.')],
    text('Просроченный тест отображается отдельно и может быть недоступен.', 'Мерзімі өткен тест бөлек көрсетіліп, қолжетімсіз болуы мүмкін.', 'An expired quiz is shown separately and may be unavailable.'),
    text('Результат попытки связан с назначенным курсом.', 'Әрекет нәтижесі тағайындалған курспен байланысты.', 'The attempt result is linked to the assigned course.'),
    text('Результат теста не заменяет подтверждение обучения, если процедура требует его отдельно.', 'Тест нәтижесі рәсім бөлек талап етсе, оқуды растауды алмастырмайды.', 'A quiz result does not replace separate training confirmation when required.')),
  topic('student-certificates', ['/certificates'], ['student'],
    text('Сертификаты', 'Сертификаттар', 'Certificates'),
    text('Просмотр выданных сертификатов и переход к их проверке.', 'Берілген сертификаттарды көру және тексеруге өту.', 'View issued certificates and open verification.'),
    [text('Откройте список выданных сертификатов.', 'Берілген сертификаттар тізімін ашыңыз.', 'Open issued certificates.'), text('Выберите номер сертификата.', 'Сертификат нөмірін таңдаңыз.', 'Select a certificate number.'), text('При необходимости откройте публичную проверку.', 'Қажет болса, ашық тексеруді ашыңыз.', 'Open public verification if needed.')],
    text('Если сертификата нет, проверьте статус завершения и подтверждения обучения.', 'Сертификат жоқ болса, аяқталу және оқуды растау мәртебесін тексеріңіз.', 'If no certificate is listed, check completion and confirmation status.'),
    text('Выданный сертификат имеет проверяемую запись.', 'Берілген сертификаттың тексерілетін жазбасы бар.', 'An issued certificate has a verifiable record.'),
    text('Список не выдаёт сертификаты сам по себе.', 'Тізімнің өзі сертификат бермейді.', 'The list does not issue certificates by itself.')),
  topic('student-learning-paths', ['/learning-paths'], ['student'],
    text('Мои программы обучения', 'Менің оқу бағдарламаларым', 'My learning programs'),
    text('Просмотр прогресса по назначенным программам и их шагам.', 'Тағайындалған бағдарламалар мен қадамдар бойынша ілгерілеуді көру.', 'Review progress through assigned programs and steps.'),
    [text('Выберите программу.', 'Бағдарламаны таңдаңыз.', 'Choose a program.'), text('Откройте доступный шаг.', 'Қолжетімді қадамды ашыңыз.', 'Open an available step.'), text('Вернитесь к программе и проверьте процент выполнения.', 'Бағдарламаға оралып, орындалу пайызын тексеріңіз.', 'Return and check the completion percentage.')],
    text('Заблокированный шаг показывает, какое предыдущее требование ещё не выполнено.', 'Бұғатталған қадам қандай алдыңғы талап орындалмағанын көрсетеді.', 'A locked step indicates which prior requirement is incomplete.'),
    text('Прогресс программы собран из статусов её курсов.', 'Бағдарлама ілгерілеуі оның курстарының мәртебелерінен жиналады.', 'Program progress is based on its course statuses.'),
    text('Обучающийся не редактирует состав или порядок программы.', 'Оқушы бағдарлама құрамын немесе ретін өзгертпейді.', 'The learner does not edit program content or order.')),
  topic('student-quiz', ['/courses/quiz'], ['student'],
    text('Тест', 'Тест', 'Quiz'),
    text('Ответьте на вопросы назначенного теста и проверьте сохранённые попытки.', 'Тағайындалған тест сұрақтарына жауап беріп, сақталған әрекеттерді тексеріңіз.', 'Answer the assigned quiz questions and review saved attempts.'),
    [text('Выберите ответ на каждый вопрос.', 'Әр сұраққа жауап таңдаңыз.', 'Choose an answer for each question.'), text('Отправьте попытку и ознакомьтесь с результатом.', 'Әрекетті жіберіп, нәтижені қараңыз.', 'Submit the attempt and review the result.'), text('После успешной попытки вернитесь в курс для следующего шага.', 'Сәтті әрекеттен кейін келесі қадам үшін курсқа оралыңыз.', 'After a successful attempt, return to the course for the next step.')],
    text('Неудачная попытка сохраняется и не завершает урок; повтор доступен в пределах лимита.', 'Сәтсіз әрекет сақталады және сабақты аяқтамайды; қайталау шек ішінде қолжетімді.', 'A failed attempt is retained and does not complete the lesson; retry is available within the limit.'),
    text('Результат попытки связан с назначенным курсом.', 'Әрекет нәтижесі тағайындалған курспен байланысты.', 'The attempt result is linked to the assigned course.'),
    text('Завершение курса подтверждается после возврата в курс и выполнения его условий.', 'Курс талаптарын орындап, курсқа оралғаннан кейін аяқталу расталады.', 'Course completion is confirmed after returning to the course and meeting its requirements.')),
  topic('student-course', ['/courses'], ['student'],
    text('Курс', 'Курс', 'Course'),
    text('Прохождение назначенного курса, уроков и связанных тестов.', 'Тағайындалған курсты, сабақтарды және байланысты тесттерді өту.', 'Complete an assigned course, lessons, and related quizzes.'),
    [text('Откройте доступный урок.', 'Қолжетімді сабақты ашыңыз.', 'Open an available lesson.'), text('Изучите материал и пройдите тест, если он есть.', 'Материалды оқып, бар болса тесттен өтіңіз.', 'Study the material and take its quiz when present.'), text('Проверьте сохранённый прогресс перед выходом.', 'Шықпас бұрын сақталған ілгерілеуді тексеріңіз.', 'Check saved progress before leaving.')],
    text('На последнем уроке проверьте итоговый статус курса и доступный результат.', 'Соңғы сабақта курс мәртебесі мен қолжетімді нәтижені тексеріңіз.', 'On the final lesson, review the course status and available result.'),
    text('Прогресс уроков и тестов виден в рамках назначенного курса.', 'Сабақтар мен тесттер ілгерілеуі тағайындалған курс ішінде көрінеді.', 'Lesson and quiz progress is visible within the assigned course.'),
    text('Курс не даёт обучающемуся доступ к редактору или административным действиям.', 'Курс оқушыға редакторға немесе әкімшілік әрекеттерге жол бермейді.', 'The course does not expose authoring or administrative actions to the learner.')),
  topic('admin-dashboard', ['/admin'], ['admin'],
    text('Обзор организации', 'Ұйым шолуы', 'Organization overview'),
    text('Быстрый доступ к настройкам тенанта, команде и отчётам.', 'Тенант параметрлеріне, командаға және есептерге жылдам қолжетімділік.', 'Quick access to tenant settings, team, and reports.'),
    [text('Проверьте сводные показатели.', 'Жинақталған көрсеткіштерді тексеріңіз.', 'Review summary indicators.'), text('Откройте нужный раздел.', 'Қажетті бөлімді ашыңыз.', 'Open the needed section.'), text('После изменения вернитесь и проверьте состояние.', 'Өзгерістен кейін оралып, күйді тексеріңіз.', 'Return after a change and verify state.')],
    text('Для добавления методиста используйте раздел команды.', 'Әдіскер қосу үшін команда бөлімін пайдаланыңыз.', 'Use the team section to add a methodologist.'),
    text('Понятный переход к административной задаче.', 'Әкімшілік тапсырмаға түсінікті өту.', 'A clear route to an administrative task.'),
    text('Обзор не даёт администратору доступ к методологическим материалам и назначениям.', 'Шолу әкімшіге әдістемелік материалдар мен тағайындауларға жол бермейді.', 'The overview does not grant content or assignment access.')),
  topic('admin-settings', ['/settings'], ['admin'],
    text('Настройки организации', 'Ұйым параметрлері', 'Organization settings'),
    text('Переход к настройкам тенанта и доступным разделам конфигурации.', 'Тенант параметрлері мен қолжетімді конфигурация бөлімдеріне өту.', 'Open tenant settings and available configuration sections.'),
    [text('Выберите нужный раздел.', 'Қажетті бөлімді таңдаңыз.', 'Choose the needed section.'), text('Проверьте текущие значения перед изменением.', 'Өзгертпес бұрын ағымдағы мәндерді тексеріңіз.', 'Review current values before changing them.'), text('Сохраните только согласованные настройки.', 'Тек келісілген параметрлерді сақтаңыз.', 'Save only approved settings.')],
    text('Перед настройкой интеграции уточните владельца и тестовый контур.', 'Интеграцияны баптамас бұрын иесі мен тест контурын нақтылаңыз.', 'Before configuring an integration, confirm its owner and test contour.'),
    text('Изменение отражается в соответствующем административном разделе.', 'Өзгеріс тиісті әкімшілік бөлімде көрсетіледі.', 'Changes are reflected in the relevant admin section.'),
    text('Не меняйте внешние подключения или расходы без отдельного разрешения владельца.', 'Иесінің бөлек рұқсатынсыз сыртқы қосылымдар мен шығындарды өзгертпеңіз.', 'Do not change external connections or spend without explicit owner approval.')),
  topic('admin-integrations', ['/admin/settings/integrations'], ['admin'],
    text('Интеграции', 'Интеграциялар', 'Integrations'),
    text('Проверка доступных подключений организации и их статуса.', 'Ұйымның қолжетімді қосылымдары мен олардың күйін тексеру.', 'Review available organization integrations and their status.'),
    [text('Откройте нужное подключение.', 'Қажетті қосылымды ашыңыз.', 'Open the needed integration.'), text('Проверьте обязательные поля и индикатор состояния.', 'Міндетті өрістер мен күй индикаторын тексеріңіз.', 'Review required fields and status indicator.'), text('Сохраните только проверенную конфигурацию и перечитайте статус.', 'Тек тексерілген конфигурацияны сақтап, күйді қайта оқыңыз.', 'Save only reviewed configuration and reread status.')],
    text('Если индикатор требует внимания, сначала проверьте сохранённые параметры.', 'Индикатор назарды қажет етсе, алдымен сақталған параметрлерді тексеріңіз.', 'If the indicator needs attention, first review saved settings.'),
    text('Состояние подключения видно без предположений о доставке внешнего сервиса.', 'Қосылым күйі сыртқы сервис жеткізуін болжамай-ақ көрінеді.', 'Connection state is visible without assuming external delivery.'),
    text('Эта справка не подтверждает работу внешнего провайдера или доставку сообщений.', 'Бұл анықтама сыртқы провайдердің жұмысын немесе хабар жеткізілуін растамайды.', 'This help does not prove external-provider operation or message delivery.')),
  topic('admin-ai', ['/admin/settings/ai'], ['admin'],
    text('Провайдеры AI', 'AI провайдерлері', 'AI providers'),
    text('Настройка разрешённых моделей и параметров AI для тенанта.', 'Тенант үшін рұқсат етілген модельдер мен AI параметрлерін баптау.', 'Configure allowed AI models and tenant parameters.'),
    [text('Проверьте назначение и область каждого параметра.', 'Әр параметрдің мақсаты мен аясын тексеріңіз.', 'Review the purpose and scope of each setting.'), text('Изменяйте только согласованные значения.', 'Тек келісілген мәндерді өзгертіңіз.', 'Change only approved values.'), text('Сохраните и проверьте отображённый статус.', 'Сақтап, көрсетілген күйді тексеріңіз.', 'Save and review the displayed status.')],
    text('Настройка генерации и эмбеддингов может быть разделена по назначению.', 'Генерация мен эмбеддинг параметрлері мақсаты бойынша бөлінуі мүмкін.', 'Generation and embedding settings may be separated by purpose.'),
    text('Тенант видит сохранённую конфигурацию AI.', 'Тенант сақталған AI конфигурациясын көреді.', 'The tenant can see saved AI configuration.'),
    text('Не включайте новый провайдер, платный тариф или секрет без отдельного разрешения.', 'Бөлек рұқсатсыз жаңа провайдерді, ақылы жоспарды немесе құпияны қоспаңыз.', 'Do not enable a new provider, paid plan, or secret without explicit approval.')),
  topic('admin-certificates', ['/admin/certificates/settings'], ['admin'],
    text('Шаблон сертификата', 'Сертификат үлгісі', 'Certificate template'),
    text('Проверка шаблона и параметров выдаваемого сертификата.', 'Берілетін сертификат үлгісі мен параметрлерін тексеру.', 'Review the certificate template and issuance settings.'),
    [text('Проверьте поля и предпросмотр.', 'Өрістер мен алдын ала қарауды тексеріңіз.', 'Review fields and preview.'), text('Сверьте текст с утверждённым вариантом.', 'Мәтінді бекітілген нұсқамен салыстырыңыз.', 'Compare text with the approved version.'), text('Сохраните согласованные изменения и снова проверьте предпросмотр.', 'Келісілген өзгерістерді сақтап, алдын ала қарауды қайта тексеріңіз.', 'Save approved changes and review the preview again.')],
    text('Предпросмотр использует демонстрационные данные сотрудника и курса.', 'Алдын ала қарау қызметкер мен курс деректерінің демонстрациялық нұсқасын пайдаланады.', 'The preview uses demonstration employee and course data.'),
    text('Шаблон готов к проверяемому использованию после сохранения.', 'Үлгі сақталғаннан кейін тексерілетін пайдалануға дайын.', 'The template is ready for review after saving.'),
    text('Настройка шаблона не выдаёт сертификат и не подтверждает завершение обучения.', 'Үлгі баптауы сертификат бермейді және оқудың аяқталғанын растамайды.', 'Template settings do not issue a certificate or confirm completion.')),
  topic('admin-training-evidence', ['/admin/training-evidence/settings'], ['admin'],
    text('Бланк подтверждения', 'Растау бланкісі', 'Training evidence form'),
    text('Настройка текста бланка и его предпросмотра.', 'Растау бланкісінің мәтінін және алдын ала қарауын баптау.', 'Configure the evidence form text and preview.'),
    [text('Проверьте вводный, подтверждающий и нижний текст.', 'Кіріспе, растау және төменгі мәтінді тексеріңіз.', 'Review the intro, confirmation, and footer text.'), text('Откройте PDF-предпросмотр.', 'PDF алдын ала қарауын ашыңыз.', 'Open the PDF preview.'), text('Сохраните только утверждённую формулировку.', 'Тек бекітілген тұжырымды сақтаңыз.', 'Save only approved wording.')],
    text('Данные в предпросмотре помечены как демонстрационные.', 'Алдын ала қараудағы деректер демонстрациялық деп белгіленген.', 'Preview data is marked as demonstration data.'),
    text('Сохранённый бланк доступен для последующей процедуры подтверждения.', 'Сақталған бланк кейінгі растау рәсіміне қолжетімді.', 'The saved form is available for the later confirmation procedure.'),
    text('Бланк сам по себе не подтверждает обучение и не создаёт сертификат.', 'Бланк өздігінен оқуды растамайды және сертификат жасамайды.', 'The form itself does not confirm learning or create a certificate.')),
  topic('admin-audit', ['/admin/audit'], ['admin'],
    text('Журнал действий', 'Әрекеттер журналы', 'Audit log'),
    text('Просмотр изменений организации с фильтром по периоду.', 'Ұйым өзгерістерін кезең бойынша сүзгілеп көру.', 'Review organization changes filtered by period.'),
    [text('Укажите период.', 'Кезеңді көрсетіңіз.', 'Set the date range.'), text('Нажмите «Применить».', '«Қолдану» түймесін басыңыз.', 'Select Apply.'), text('Проверьте запись, аккаунт, объект и подробности.', 'Жазбаны, аккаунтты, нысанды және мәліметтерді тексеріңіз.', 'Review the actor, account, object, and details.')],
    text('Если строк нет, по выбранным фильтрам нет подходящих записей; пустые даты не ограничивают поиск по периоду.', 'Жолдар болмаса, таңдалған сүзгілерге сәйкес жазбалар жоқ; күндерді бос қалдыру кезең бойынша сүзуді шектемейді.', 'No rows means no records match the selected filters; leaving the dates blank does not limit the period.'),
    text('Получается проверяемая история изменений.', 'Өзгерістердің тексерілетін тарихы пайда болады.', 'You get a reviewable change history.'),
    text('Журнал не отменяет действие и не удаляет историю увольнений.', 'Журнал әрекетті кері қайтармайды және жұмыстан шығу тарихын жоймайды.', 'The log does not undo actions or remove termination history.')),
  topic('admin-kiosks', ['/admin/kiosks'], ['admin'],
    text('Киоски для цехов', 'Цех киоскілері', 'Workshop kiosks'),
    text('Управление киосками и PIN-кодами сотрудников.', 'Киосктер мен қызметкер PIN-кодтарын басқару.', 'Manage kiosks and employee PINs.'),
    [text('Проверьте название, локацию и статус киоска.', 'Киоск атауын, орнын және күйін тексеріңіз.', 'Review kiosk name, location, and status.'), text('Для PIN выберите сотрудника.', 'PIN үшін қызметкерді таңдаңыз.', 'Select an employee for a PIN.'), text('Скопируйте или распечатайте данные только для согласованного места.', 'Деректерді тек келісілген орын үшін көшіріңіз немесе басып шығарыңыз.', 'Copy or print details only for the approved location.')],
    text('Перед выдачей PIN убедитесь, что сотрудник выбран правильно.', 'PIN бермес бұрын дұрыс қызметкер таңдалғанын тексеріңіз.', 'Before issuing a PIN, verify the correct employee is selected.'),
    text('Киоск и его статус видны в списке управления.', 'Киоск пен оның күйі басқару тізімінде көрінеді.', 'Kiosk and status are visible in the management list.'),
    text('PIN — чувствительный доступ; не публикуйте его в общем месте.', 'PIN — сезімтал қолжетімділік; оны ортақ жерде жарияламаңыз.', 'A PIN is sensitive access; do not post it publicly.')),
  topic('admin-course-approvals', ['/admin/course-approvals'], ['admin', 'methodologist'],
    text('Согласование курсов', 'Курстарды келісу', 'Course approvals'),
    text('Настройка обязательной проверки, создание запроса и просмотр решений по курсам.', 'Міндетті тексеруді баптау, сұрау жасау және курстар бойынша шешімдерді көру.', 'Configure required review, create requests, and view course decisions.'),
    [text('Выберите курс и проверьте или измените показанную политику обязательной проверки.', 'Курсты таңдап, көрсетілген міндетті тексеру саясатын тексеріңіз немесе өзгертіңіз.', 'Select a course and review or change the displayed required-review policy.'), text('Создайте снимок и запрос только для готовой версии курса.', 'Сурет пен сұрауды тек дайын курс нұсқасы үшін жасаңыз.', 'Create a snapshot and request only for a ready course version.'), text('Обновите статусы запросов и проверьте решение рецензента.', 'Сұрау мәртебелерін жаңартып, рецензент шешімін тексеріңіз.', 'Refresh request statuses and review the reviewer decision.')],
    text('Перед запросом выберите курс и проверьте его политику; требования к рецензентам, если они не показаны здесь, настраивает администратор тенанта.', 'Сұрау алдында курсты таңдап, саясатын тексеріңіз; рецензент талаптары мұнда көрсетілмесе, оларды тенант әкімшісі баптайды.', 'Before requesting, select the course and review its policy; if reviewer requirements are not shown here, the tenant admin configures them.'),
    text('Курс получает проверяемый статус согласования.', 'Курс тексерілетін келісу мәртебесін алады.', 'The course receives a reviewable approval status.'),
    text('Согласование не заменяет проверку содержания и не публикует курс без предусмотренного решения.', 'Келісу мазмұн тексеруін алмастырмайды және көзделген шешімсіз курсты жарияламайды.', 'Approval does not replace content review or publish without the required decision.')),
  topic('invitations', ['/invitations'], ['methodologist'],
    text('Приглашения сотрудников', 'Қызметкерлер шақырулары', 'Employee invitations'),
    text('Создание и контроль ссылок-приглашений для сотрудников.', 'Қызметкерлерге шақыру сілтемелерін жасау және бақылау.', 'Create and track employee invitation links.'),
    [text('Введите рабочий email сотрудника и создайте ссылку.', 'Қызметкердің жұмыс email-ын енгізіп, сілтемені жасаңыз.', 'Enter the employee work email and create an invitation link.'), text('Передайте ссылку рабочим каналом; приглашение не сбрасывает пароль и не заменяет подтверждение входа.', 'Сілтемені жұмыс арнасымен жіберіңіз; шақыру құпиясөзді қалпына келтірмейді және кіруді растауды алмастырмайды.', 'Share the link through a work channel; an invitation does not reset a password or replace sign-in confirmation.'), text('Обновите историю и проверьте срок, статус и доставку приглашения.', 'Тарихты жаңартып, шақырудың мерзімін, мәртебесін және жеткізілуін тексеріңіз.', 'Refresh the history and review invitation expiry, status, and delivery.')],
    text('В демо-режиме создание аккаунтов сотрудников и ссылок-приглашений заблокировано.', 'Демо режимінде қызметкер аккаунттары мен шақыру сілтемелерін жасау бұғатталған.', 'Demo mode blocks creating employee accounts and invitation links.'),
    text('История показывает принятие приглашения и состояние доставки, но не подтверждает открытие письма.', 'Тарих шақырудың қабылдануы мен жеткізу күйін көрсетеді, бірақ хаттың ашылғанын растамайды.', 'History shows invitation acceptance and delivery state, but does not confirm that the email was opened.'),
    text('Не передавайте ссылку публично; проверьте адрес и срок действия перед отправкой.', 'Сілтемені ашық таратпаңыз; жібермес бұрын мекенжайы мен жарамдылық мерзімін тексеріңіз.', 'Do not share the link publicly; verify the address and expiry before sending.')),
  topic('admin-mandatory-training', ['/mandatory-training'], ['admin'],
    text('Обязательные требования', 'Міндетті талаптар', 'Mandatory requirements'),
    text('Просмотр сотрудников, у которых обязательное обучение требует внимания.', 'Міндетті оқуы назарды қажет ететін қызметкерлерді көру.', 'Review employees whose mandatory training needs attention.'),
    [text('Найдите сотрудника по поиску и при необходимости выберите состояние требования.', 'Қызметкерді іздеу арқылы тауып, қажет болса талап күйін таңдаңыз.', 'Search for an employee and, if needed, choose a requirement state.'), text('Нажмите «Применить» и проверьте карточки и строки результата.', '«Қолдану» түймесін басып, нәтиже карточкалары мен жолдарын тексеріңіз.', 'Select Apply and review the result cards and rows.'), text('Разверните сведения об источнике требования в строке или карточке и проверьте указанное действие.', 'Жолда немесе карточкада талап көзі туралы мәліметті ашып, көрсетілген әрекетті тексеріңіз.', 'Expand the requirement-source details in the row or card and review the stated action.')],
    text('Проверьте сотрудника со статусом «Без назначения» и разберите указанную причину.', '«Тағайындау жоқ» күйіндегі қызметкерді тексеріп, көрсетілген себепті талдаңыз.', 'Review an employee marked Missing assignment and inspect the stated reason.'),
    text('Получается проверяемая картина обязательных требований и текущих состояний.', 'Міндетті талаптар мен ағымдағы күйлердің тексерілетін көрінісі алынады.', 'You get a reviewable view of mandatory requirements and current states.'),
    text('Это просмотр для роли admin: он не создаёт назначения, курсы или экспорт.', 'Бұл admin рөліне арналған көрініс: ол тағайындау, курс немесе экспорт жасамайды.', 'This is a read-only admin view; it does not create assignments, courses, or exports.')),
  topic('admin-training-log', ['/training-log'], ['admin'],
    text('Журнал обучения', 'Оқу журналы', 'Training log'),
    text('Просмотр статусов обучения сотрудников и истории их прохождения.', 'Қызметкерлердің оқу мәртебелері мен өту тарихын көру.', 'Review employee learning statuses and completion history.'),
    [text('Найдите сотрудника по имени, email или табельному номеру.', 'Қызметкерді аты, email-ы немесе табель нөмірі бойынша табыңыз.', 'Search for an employee by name, email, or personnel number.'), text('Уточните результат по статусу, типу обучения, датам и при необходимости включите историю.', 'Нәтижені мәртебе, оқу түрі және күндер бойынша нақтылап, қажет болса тарихты қосыңыз.', 'Refine the result by status, delivery type, and dates, and include history when needed.'), text('Проверьте строки журнала и выгрузите CSV только для согласованной рабочей цели.', 'Журнал жолдарын тексеріп, CSV файлын тек келісілген жұмыс мақсаты үшін жүктеңіз.', 'Review the log rows and export CSV only for an approved business purpose.')],
    text('Найдите сотрудников со статусом «Просрочено» за выбранный период и проверьте прогресс.', 'Таңдалған кезеңде «Мерзімі өткен» мәртебесіндегі қызметкерлерді тауып, прогресті тексеріңіз.', 'Find employees marked Overdue in the selected period and review progress.'),
    text('Получается проверяемая история статусов обучения по сотрудникам.', 'Қызметкерлер бойынша оқу мәртебелерінің тексерілетін тарихы алынады.', 'You get a reviewable history of employee learning statuses.'),
    text('Это просмотр для роли admin: он не создаёт курсы и назначения; название курса доступно только для чтения.', 'Бұл admin рөліне арналған көрініс: ол курс пен тағайындау жасамайды; курс атауы тек оқуға қолжетімді.', 'This is a read-only admin view; it does not create courses or assignments, and the course title is read-only.')),
  topic('superadmin', ['/admin/super'], ['superadmin'],
    text('Платформа и тенанты', 'Платформа және тенанттар', 'Platform and tenants'),
    text('Обзор организаций платформы и переход к доступным разделам управления.', 'Платформа ұйымдарының шолуы және қолжетімді басқару бөлімдеріне өту.', 'Review platform organizations and open the available management sections.'),
    [text('Найдите нужный тенант.', 'Қажетті тенантты табыңыз.', 'Find the needed tenant.'), text('Откройте карточку и проверьте сводку.', 'Карточканы ашып, шолуды тексеріңіз.', 'Open its card and review the summary.'), text('Для изменений используйте отдельное подтверждённое действие.', 'Өзгерістер үшін бөлек расталған әрекетті пайдаланыңыз.', 'Use a separately confirmed action for changes.')],
    text('Сначала сверяйте идентичность тенанта и окружения.', 'Алдымен тенант пен ортаның сәйкестігін тексеріңіз.', 'First verify tenant and environment identity.'),
    text('Оператор платформы видит только разрешённый контекст управления.', 'Платформа операторы тек рұқсат етілген басқару контекстін көреді.', 'The platform operator sees only the permitted management context.'),
    text('Проверяйте организацию и окружение перед изменениями; очистка и провайдерские настройки требуют отдельного подтверждения.', 'Өзгерістер алдында ұйым мен ортаны тексеріңіз; тазалау және провайдер баптаулары бөлек растауды қажет етеді.', 'Verify the organization and environment before changes; cleanup and provider settings require separate confirmation.')),
  topic('superadmin-operations', ['/admin/super/operations'], ['superadmin'],
    text('Операции платформы', 'Платформа операциялары', 'Platform operations'),
    text('Сводка состояния фоновых задач, документов, базы данных и процесса API.', 'Фондық тапсырмалар, құжаттар, дерекқор және API процесі күйінің шолуы.', 'A status summary for background jobs, documents, the database, and the API process.'),
    [text('Обновите сводку.', 'Шолуды жаңартыңыз.', 'Refresh the summary.'), text('Проверьте ошибки обработки и недоступные компоненты по показанным метрикам.', 'Көрсетілген метрикалардан өңдеу қателері мен қолжетімсіз компоненттерді тексеріңіз.', 'Review processing errors and unavailable components in the displayed metrics.'), text('Перед кнопкой восстановления или очистки проверьте предупреждение, область и подтверждение.', 'Қалпына келтіру немесе тазалау түймесінің алдында ескерту, ауқым және растауды тексеріңіз.', 'Before recovery or cleanup, review the warning, scope, and confirmation.')],
    text('Пустая или недоступная метрика означает, что состояние не подтверждено этой сводкой.', 'Бос немесе қолжетімсіз метрика бұл шолу күйді растамағанын білдіреді.', 'An empty or unavailable metric means this summary has not confirmed the state.'),
    text('Оператор получает сводку состояния с явными предупреждениями.', 'Оператор нақты ескертулері бар күй шолуын алады.', 'The operator gets a status summary with explicit warnings.'),
    text('Кнопки очистки и восстановления являются потенциально изменяющими; не запускайте их только для проверки.', 'Тазалау және қалпына келтіру түймелері өзгеріс енгізуі мүмкін; тек тексеру үшін іске қоспаңыз.', 'Cleanup and recovery buttons may mutate state; do not run them just to inspect.')),
  topic('superadmin-providers', ['/admin/providers'], ['superadmin'],
    text('Провайдеры платформы', 'Платформа провайдерлері', 'Platform providers'),
    text('Просмотр ключей провайдеров и порядка маршрутизации моделей.', 'Провайдер кілттері мен модельдерді бағыттау ретін көру.', 'Review provider keys and model routing order.'),
    [text('Проверьте активные ключи и последние ошибки.', 'Белсенді кілттер мен соңғы қателерді тексеріңіз.', 'Review active keys and recent errors.'), text('Сверьте текущий порядок моделей и доступные варианты маршрутизации.', 'Модельдердің ағымдағы ретін және қолжетімді бағыттау нұсқаларын салыстырыңыз.', 'Review the current model order and available routing options.'), text('Сохраняйте или тестируйте изменения только после отдельного подтверждения области и последствий.', 'Өзгерістерді тек ауқым мен салдарын бөлек растағаннан кейін сақтаңыз немесе тексеріңіз.', 'Save or test changes only after separately confirming scope and impact.')],
    text('Перед изменением сохраните текущий порядок и ожидаемый план отката.', 'Өзгертпес бұрын ағымдағы ретті және кері қайту жоспарын сақтаңыз.', 'Before changing, record the current order and rollback plan.'),
    text('Маршрутизация отражает сохранённый порядок моделей.', 'Маршрутизация модельдердің сақталған ретін көрсетеді.', 'Routing reflects the saved model order.'),
    text('Не добавляйте ключи, платные ресурсы или новых провайдеров без отдельного разрешения.', 'Бөлек рұқсатсыз кілттерді, ақылы ресурстарды немесе жаңа провайдерлерді қоспаңыз.', 'Do not add keys, paid resources, or providers without separate authorization.')),
];

export const CONTEXTUAL_HELP_TOPIC_IDS = TOPICS.map((topic) => topic.id);

function pathMatches(pathname: string, candidate: string): boolean {
  return pathname === candidate || pathname.startsWith(`${candidate}/`);
}

function localized(value: LocalizedText, locale: string): string {
  return value[locale as HelpLocale] || value.ru;
}

export function getContextualHelp(
  pathname: string,
  role: string | null | undefined,
  locale: string,
): ContextualHelpContent | null {
  const topic = TOPICS.filter(
    (candidate) => candidate.roles.includes(role as AppRole)
      && candidate.paths.some((path) => pathMatches(pathname, path)),
  ).toSorted((a, b) => {
    const longestPath = (definition: HelpTopicDefinition) => Math.max(...definition.paths.map((path) => path.length));
    return longestPath(b) - longestPath(a);
  })[0];
  if (!topic) return null;
  return {
    id: topic.id,
    title: localized(topic.title, locale),
    purpose: localized(topic.purpose, locale),
    steps: topic.steps.map((step) => localized(step, locale)),
    example: localized(topic.example, locale),
    result: localized(topic.result, locale),
    important: localized(topic.important, locale),
  };
}
