import axios from 'axios';

import { api } from '@/lib/api';

export const EDITOR_ASSISTANT_INTENTS = ['rewrite_wording', 'add_context', 'regenerate_distractors', 'balance_answer_length', 'add_or_rewrite_explanation'] as const;
export type EditorAssistantIntent = (typeof EDITOR_ASSISTANT_INTENTS)[number];
type Path = 'question.text' | 'question.answer_options' | 'question.explanation';
type State = 'pending' | 'completed' | 'failed';
type Applicability = 'applicable' | 'applicable_with_warnings' | 'requires_new_draft_revision' | 'not_applicable' | 'stale';
type ValidationStatus = 'pass' | 'warn' | 'fail';

export interface EditorAssistantPreviewRequest { request_key: string; preview_key: string; intent: EditorAssistantIntent; instruction: string; }
interface Option { choice_id: string; text: string; is_correct: boolean; }
interface Issue { code: string; message: string; blocking: boolean; field_path: Path; }
interface SourceReference { source_id: string; document_title: string; locator: string; }
interface Provenance { prompt_version: string; generator_version: string; validator_version: string; }
interface Failure { error_code: string; message: string; }
export interface EditorAssistantPatchOperation { operation: 'replace'; field_path: Path; before_value: string | Option[] | null; after_value: string | Option[] | null; }
export interface EditorAssistantPreviewResponse { request_id: string; preview_id: string; state: State; applicability: Applicability; base_snapshot_token: string; operations: EditorAssistantPatchOperation[]; validation: { status: ValidationStatus; issues: Issue[] } | null; source: { source_reference_count: number; references: SourceReference[] }; provenance: Provenance | null; failure: Failure | null; }
export class EditorAssistantPreviewApiError extends Error { constructor(message: string, public readonly status: number | null, public readonly safeDetail: string | null) { super(message); this.name = 'EditorAssistantPreviewApiError'; } }

const FAILURE: Record<string, readonly [string, Applicability]> = { provider_timeout:['Сервис генерации не ответил вовремя.','not_applicable'],provider_unavailable:['Сервис генерации временно недоступен.','not_applicable'],provider_output_unparseable:['Не удалось обработать ответ сервиса генерации.','not_applicable'],contract_violation:['Предложение не соответствует требованиям редактора.','not_applicable'],validation_blocked:['Предложение не прошло проверку качества.','not_applicable'],stale_base_version:['Вопрос был изменён. Обновите данные и повторите запрос.','stale'],rejected_out_of_scope:['Предложение выходит за область выбранного вопроса.','not_applicable'],source_evidence_unavailable:['Для вопроса недоступны подтверждающие материалы.','not_applicable'],requires_new_draft_revision:['Для опубликованного курса требуется новая черновая версия.','requires_new_draft_revision'],internal_error:['Не удалось подготовить предложение.','not_applicable'] };
const ISSUE_MESSAGES: Record<string,string> = { invalid_operation:'Предложение содержит недопустимое изменение.',out_of_scope:'Предложение выходит за область выбранного вопроса.',missing_source_evidence:'Недостаточно данных из исходного документа.',protected_field:'Предложение изменяет защищённое поле.',invalid_base_snapshot:'Исходная версия вопроса изменилась.',published_content_requires_draft:'Для опубликованного курса требуется новая черновая версия.',provider_output_invalid:'Предложение не прошло проверку качества.',correct_answer_length_signal:'Длина правильного ответа заметно отличается от вариантов.',correct_answer_style_signal:'Стиль или маркеры уверенности выделяют правильный ответ.',implausible_distractors:'Есть вариант, который не отвечает на вопрос или выглядит неправдоподобно.',multiple_plausible_correct_answers:'Несколько вариантов отмечены как потенциально правильные по явному сигналу.',unsupported_correct_answer:'Правильный ответ не подтверждён разрешённым источником.',malformed_question:'Вопрос или варианты ответа составлены некорректно.',duplicate_question:'Вопрос дублирует другой вопрос в этом тесте.',rote_recall_only:'Вопрос похож на проверку запоминания без применения знаний.',language_or_translation_problem:'Есть явный сигнал языковой или переводческой проблемы.',explanation_leaked_into_answer:'Объяснение попало в текст варианта ответа.',other:'Найдена дополнительная проблема качества.' };
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, OPAQUE=/^[A-Za-z0-9][A-Za-z0-9_-]{15,159}$/, REFERENCE=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,119}$/, VERSION=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,119}$/;
const PATHS: readonly Path[]=['question.text','question.answer_options','question.explanation']; const CONTROL_CHARACTER=/[\u0000-\u001F\u007F]/; const MAX_PREVIEW_RESPONSE_BYTES=65_536;
function invalid():never { throw new EditorAssistantPreviewApiError('Помощник вернул некорректное предложение. Повторите запрос позже.',200,null); }
function invalidRequest():never { throw new EditorAssistantPreviewApiError('Проверьте данные запроса помощнику и повторите попытку.',null,null); }
function isRecord(value:unknown):value is Record<string,unknown> { return value!==null&&typeof value==='object'&&!Array.isArray(value); }
function exactObject(value:unknown,keys:readonly string[]):Record<string,unknown> { if(!isRecord(value))invalid();let count=0;for(const key in value){if(!Object.prototype.hasOwnProperty.call(value,key))continue;count+=1;if(count>keys.length||!keys.includes(key))invalid();}if(count!==keys.length||keys.some((key)=>!Object.prototype.hasOwnProperty.call(value,key)))invalid();return value; }
function characterCountWithin(value:string,maximum:number):number|null { if(value.length>maximum*2)return null;let count=0;for(const _character of value){count+=1;if(count>maximum)return null;}return count; }
function boundedString(value:unknown,minimum=1,maximum=4000,pattern?:RegExp,rejectControls=false):string { if(typeof value!=='string')invalid();const count=characterCountWithin(value,maximum);if(count===null||count<minimum||(pattern&&!pattern.test(value))||(rejectControls&&CONTROL_CHARACTER.test(value)))invalid();return value; }
function boundedArray(value:unknown,minimum=0,maximum=20):unknown[] { if(!Array.isArray(value)||value.length<minimum||value.length>maximum)invalid();return value; }
function parseUuid(value:unknown):string { return boundedString(value,36,36,UUID); }
function requestUuid(value:unknown):string { if(typeof value!=='string'||value.length!==36||!UUID.test(value))invalidRequest();return value; }
function requestInstruction(value:unknown):string { if(typeof value!=='string')invalidRequest();const count=characterCountWithin(value,4000);if(count===null||count<1)invalidRequest();return value; }
function requestIntent(value:unknown):EditorAssistantIntent { if(typeof value!=='string'||!EDITOR_ASSISTANT_INTENTS.includes(value as EditorAssistantIntent))invalidRequest();return value as EditorAssistantIntent; }
function parsePath(value:unknown):Path { if(typeof value!=='string'||!PATHS.includes(value as Path))invalid();return value as Path; }
function parseOptions(value:unknown):Option[] { const rawOptions=boundedArray(value,2,20);const parsedOptions=rawOptions.map((entry):Option=>{const option=exactObject(entry,['choice_id','text','is_correct']);if(typeof option.is_correct!=='boolean')invalid();return {choice_id:parseUuid(option.choice_id),text:boundedString(option.text,1,1000),is_correct:option.is_correct};});if(new Set(parsedOptions.map((option)=>option.choice_id)).size!==parsedOptions.length||parsedOptions.filter((option)=>option.is_correct).length!==1)invalid();return parsedOptions; }
function parsePatchValue(value:unknown,fieldPath:Path):string|Option[]|null { if(fieldPath==='question.explanation'&&value===null)return null;if(fieldPath==='question.answer_options')return parseOptions(value);return boundedString(value,1,fieldPath==='question.explanation'?6000:4000); }
function parseOperation(value:unknown):EditorAssistantPatchOperation { const operation=exactObject(value,['operation','field_path','before_value','after_value']);if(operation.operation!=='replace')invalid();const fieldPath=parsePath(operation.field_path),beforeValue=parsePatchValue(operation.before_value,fieldPath),afterValue=parsePatchValue(operation.after_value,fieldPath);if(JSON.stringify(beforeValue)===JSON.stringify(afterValue))invalid();if(Array.isArray(beforeValue)&&Array.isArray(afterValue)){const sameIdentityAndOrder=beforeValue.length===afterValue.length&&beforeValue.every((option,index)=>option.choice_id===afterValue[index]?.choice_id);const beforeCorrect=beforeValue.find((option)=>option.is_correct),afterCorrect=afterValue.find((option)=>option.is_correct);if(!sameIdentityAndOrder||!beforeCorrect||!afterCorrect||beforeCorrect.choice_id!==afterCorrect.choice_id||beforeCorrect.text!==afterCorrect.text)invalid();}return {operation:'replace',field_path:fieldPath,before_value:beforeValue,after_value:afterValue}; }
function parseValidation(value:unknown):EditorAssistantPreviewResponse['validation'] { if(value===null)return null;const validation=exactObject(value,['status','issues']);const statusValue=validation.status;if(statusValue!=='pass'&&statusValue!=='warn'&&statusValue!=='fail')invalid();const status:ValidationStatus=statusValue;const issues=boundedArray(validation.issues,0,20).map((entry):Issue=>{const issue=exactObject(entry,['code','message','blocking','field_path']);const code=boundedString(issue.code,1,4000),message=boundedString(issue.message);if(typeof issue.blocking!=='boolean'||!(code in ISSUE_MESSAGES)||message!==ISSUE_MESSAGES[code])invalid();return {code,message,blocking:issue.blocking,field_path:parsePath(issue.field_path)};});if((status==='pass'&&issues.length>0)||(status==='warn'&&(!issues.length||issues.some((issue)=>issue.blocking)))||(status==='fail'&&!issues.some((issue)=>issue.blocking)))invalid();return {status,issues}; }
function parseProvenance(value:unknown):Provenance|null { if(value===null)return null;const provenance=exactObject(value,['prompt_version','generator_version','validator_version']);return {prompt_version:boundedString(provenance.prompt_version,1,120,VERSION),generator_version:boundedString(provenance.generator_version,1,120,VERSION),validator_version:boundedString(provenance.validator_version,1,120,VERSION)}; }
function parseFailure(value:unknown):Failure|null { if(value===null)return null;const failure=exactObject(value,['error_code','message']);const errorCode=boundedString(failure.error_code),message=boundedString(failure.message);if(!(errorCode in FAILURE)||message!==FAILURE[errorCode][0])invalid();return {error_code:errorCode,message}; }
function parseResponse(value:unknown):EditorAssistantPreviewResponse { const root=exactObject(value,['request_id','preview_id','state','applicability','base_snapshot_token','operations','validation','source','provenance','failure']);const stateValue=root.state,applicabilityValue=root.applicability;if(stateValue!=='pending'&&stateValue!=='completed'&&stateValue!=='failed')invalid();if(applicabilityValue!=='applicable'&&applicabilityValue!=='applicable_with_warnings'&&applicabilityValue!=='requires_new_draft_revision'&&applicabilityValue!=='not_applicable'&&applicabilityValue!=='stale')invalid();const state:State=stateValue,applicability:Applicability=applicabilityValue;const operations=boundedArray(root.operations,0,3).map((entry)=>parseOperation(entry));if(new Set(operations.map((operation)=>operation.field_path)).size!==operations.length)invalid();const source=exactObject(root.source,['source_reference_count','references']);const sourceReferenceCount=source.source_reference_count;if(typeof sourceReferenceCount!=='number'||!Number.isInteger(sourceReferenceCount)||sourceReferenceCount<0||sourceReferenceCount>8)invalid();const references=boundedArray(source.references,0,8).map((entry):SourceReference=>{const reference=exactObject(entry,['source_id','document_title','locator']);return {source_id:boundedString(reference.source_id,1,120,REFERENCE),document_title:boundedString(reference.document_title,1,240,undefined,true),locator:boundedString(reference.locator,1,240,undefined,true)};});if(sourceReferenceCount!==references.length||new Set(references.map((reference)=>reference.source_id)).size!==references.length)invalid();const validation=parseValidation(root.validation),provenance=parseProvenance(root.provenance),failure=parseFailure(root.failure);if(state==='pending'&&(applicability!=='not_applicable'||operations.length>0||validation!==null||provenance!==null||failure!==null||references.length>0))invalid();if(state==='completed'&&(!(applicability==='applicable'||applicability==='applicable_with_warnings')||operations.length===0||validation===null||provenance===null||failure!==null||references.length===0||(applicability==='applicable'&&validation.status!=='pass')||(applicability==='applicable_with_warnings'&&validation.status!=='warn')))invalid();if(state==='failed'&&(operations.length>0||validation!==null||provenance!==null||failure===null||references.length>0||FAILURE[failure.error_code][1]!==applicability))invalid();const result:EditorAssistantPreviewResponse={request_id:parseUuid(root.request_id),preview_id:parseUuid(root.preview_id),state,applicability,base_snapshot_token:boundedString(root.base_snapshot_token,16,160,OPAQUE),operations,validation,source:{source_reference_count:sourceReferenceCount,references},provenance,failure};const projectedJson=JSON.stringify(result);if(new TextEncoder().encode(projectedJson).length>MAX_PREVIEW_RESPONSE_BYTES)invalid();return result; }
const HTTP:Record<number,string>={401:'Сессия истекла. Войдите снова и повторите запрос.',403:'У вас нет доступа к помощнику для этого вопроса.',404:'Вопрос или его исходные материалы больше недоступны.',409:'Вопрос изменился или запрос конфликтует с предыдущим. Обновите данные и повторите вручную.',422:'Помощник не может подготовить предложение для этого вопроса или инструкции.',500:'Не удалось подготовить предложение. Повторите попытку позже.'};
export async function requestQuestionAssistantPreview(quizId:string,questionId:string,request:EditorAssistantPreviewRequest):Promise<EditorAssistantPreviewResponse>{try{const body:EditorAssistantPreviewRequest={request_key:requestUuid(request.request_key),preview_key:requestUuid(request.preview_key),intent:requestIntent(request.intent),instruction:requestInstruction(request.instruction)};const response=await api.post<unknown>(`/v1/quizzes/${requestUuid(quizId)}/questions/${requestUuid(questionId)}/assistant/preview`,body);return parseResponse(response.data);}catch(error){if(error instanceof EditorAssistantPreviewApiError)throw error;if(axios.isAxiosError(error)){const status=error.response?.status??null;const detail=(error.response?.data as {detail?:unknown}|undefined)?.detail;const safeDetail=typeof detail==='string'&&characterCountWithin(detail,240)!==null?detail:null;throw new EditorAssistantPreviewApiError((status!==null&&HTTP[status])||'Не удалось связаться с помощником.',status,safeDetail);}throw new EditorAssistantPreviewApiError('Не удалось связаться с помощником.',null,null);}}
